ably-ios/ARTHttpPaginatedResult.h, ably-ios/ARTHttpPaginatedResult.m, ably-ios/ARTPaginatedResult.h, ably-ios/ARTPaginatedResult.m, ably-ios/ARTRealtime.h, ably-ios/ARTRealtime.m, ably-ios/ARTRest.h, ably-ios/ARTRest.m, ably-ios/ARTStats.h, ably-ios/ARTStats.m, ably-ios/ably.h, ably.xcodeproj/project.pbxproj, ablySpec/RestClient.stats.swift, ablySpec/RestClient.swift, ablySpec/TestUtilities.swift
Add a new -[ARTRest stats:callback:] method that replaces the old stats API. Along with it comes ARTStatsQuery that describes query options such as direction, limit, etc.
Add tests for it all.
=> RestClient#stats

ably-ios/ARTAuth.m, ably-ios/ARTAuthOptions.m, ably-ios/ARTAuthTokenParams.m, ably-ios/ARTTypes.h, ably-ios/ARTTypes.m
I removed `canRequestToken`. It isn't necessary because the constructor does the validation.
Fixed `isBasicAuth` with:
> _It defaults to basic auth if the `keyValue` is provided, and there is no `clientId` specified. In this case, however, `useTokenAuth` forces token auth to be used._
=> Auth.canRequestToken and Auth.validate revision

ably-ios/ARTAuth.h, ably-ios/ARTAuth.m, ably-ios/ARTAuthOptions.h, ably-ios/ARTAuthOptions.m, ably-ios/ARTAuthTokenDetails.m, ably-ios/ARTAuthTokenParams.h, ably-ios/ARTAuthTokenParams.m, ably-ios/ARTAuthTokenRequest.h, ably-ios/ARTAuthTokenRequest.m, ably-ios/ARTHttp.h, ably-ios/ARTHttp.m, ably-ios/ARTJsonEncoder.m, ably-ios/ARTPaginatedResult.m, ably-ios/ARTRest+Private.h, ably-ios/ARTRest.m, ably-ios/ARTRestChannel.m, ably-ios/ARTTypes.h, ably-ios/ARTTypes.m, ablySpec/Auth.swift, ablySpec/TestUtilities.swift
- Auth.authorise was missing the possibility of receiving just an access token.
- Auth.options.clientId can be nil.
- Sign TokenRequest with clientId=* when the user is anonymous.
- Rest.calculateAuthorization was missing the Auth.authorise for token reusability.
⚠️
`RAS7a1` and `RAS7a2` are failing. Will check that on the next PR.
=> Client manage token requests

ably-ios/ARTClientOptions.h, ably-ios/ARTClientOptions.m, ably-ios/ARTEventEmitter.m, ably-ios/ARTJsonEncoder.m, ably-ios/ARTLog.h, ably-ios/ARTLog.m, ably-ios/ARTRealtime+Private.h, ably-ios/ARTRealtime.h, ably-ios/ARTRealtime.m, ably-ios/ARTRest.m, ably-ios/ARTTypes.h, ably-ios/ARTTypes.m, ably-ios/ARTWebSocketTransport.h, ably-ios/ARTWebSocketTransport.m, ably.xcodeproj/project.pbxproj, ablySpec/RealtimeClient.swift, ablySpec/TestUtilities.swift
- `RTC1` is passing.
Next on new PR:
- `ARTError` need to be a `NSError`.
- Channels are not working.
=> Realtime transport auth fixed (RTC1)

ably-ios/ARTAuthOptions.m, ably-ios/ARTPresence.m, ably-ios/ARTRealtimeChannel.h, ably-ios/ARTRealtimeChannel.m, ably-ios/ARTRestChannel.m, ably-iosTests/ARTRealtimeAttachTest.m, ably-iosTests/ARTRealtimeChannelHistoryTest.m, ably-iosTests/ARTRealtimeCryptoTest.m, ably-iosTests/ARTRealtimeMessageTest.m
- Bugfix: Channel had is own clientId string. Changed to readonly property (proxy of auth.clientId)
- Bugfix: when we copy a ClientOptions, the tokenDetails were always instanciated
- Bugfix: ARTRealtimeChannel wasn't overriding the history method
=> ObjC tests: fixed bad response

ably-ios/ARTChannel+Private.h, ably-ios/ARTChannel.h, ably-ios/ARTChannel.m, ably-ios/ARTPresence.h, ably-ios/ARTPresence.m, ably-ios/ARTPresenceMap.h, ably-ios/ARTRealtimeChannel.h, ably-ios/ARTRealtimeChannel.m, ably-ios/ARTRealtimeChannelSubscription.h, ably-ios/ARTRealtimeChannelSubscription.m, ably-ios/ARTRealtimePresence.h, ably-ios/ARTRealtimePresence.m, ably-ios/ARTRestChannel+Private.h, ably-ios/ARTRestChannel.h, ably-ios/ARTRestChannel.m, ably-ios/ARTRestPresence.h, ably-ios/ARTRestPresence.m, ably-ios/ably.h, ably-ios/ably.modulemap, ably-iosTests/ARTRealtimeAttachTest.m, ably-iosTests/ARTRealtimePresenceHistoryTest.m, ably-iosTests/ARTRealtimePresenceTest.m, ably-iosTests/ARTTestUtil.m, ably.xcodeproj/project.pbxproj
- (Conflicts) Separated base ARTPresence: ARTRealtimePresence and ARTRestPresence
- ARTRestPresence has base class for ARTRealtimePresence
=> Presence#history wasn't working (infinite recursion)

ably-ios/ARTRealtime.m, ably-ios/ARTRealtimeTransport.h, ably-ios/ARTStatus.h, ably-ios/ARTStatus.m, ably-ios/ARTWebSocketTransport.m, ably-iosTests/ARTRealtimeAttachTest.m, ably-iosTests/ARTTestUtil.h, ably-iosTests/ARTTestUtil.m
=> ObjC tests: ARTRealtimeAttachTest

ably-ios/ARTAuth+Private.h, ably-ios/ARTAuth.m, ablySpec/RestClient.swift, ablySpec/TestUtilities.swift
Reference:
> (RSC9) Uses Auth to establish what authentication scheme to use, how to authenticate, and automatic issuing of tokens when necessary
=> Swift tests: RSC9

.travis.yml, Podfile, Podfile.lock
Updated pods:
- Nimble 3.0.0 (was 2.0.0)
- Quick 0.8.0 (was 0.6.0)
- SocketRocket 0.4.2 (was 0.4.1)
- SwiftyJSON 2.3.1 (was 2.3.0)
=> Travis: Freeze dependencies

ably-iosTests/ARTRealtimeChannelHistoryTest.m, ably-iosTests/ARTRestChannelHistoryTest.m
Sometimes it was working, sometimes not.
The `XCTestExpectation.fulfill` was misplaced.
=> ObjC tests: TimeForwards and TimeBackwards

ablySpec/RealtimeClient.connection.swift
Tests were intermitently failing because of timing. This uses the
same strategy as the RTN8b test above.
This should be merged with some priority so that other PR tests
can pass more consistently.
=> waitUntil instead of toEventually in RTN9b test.

ablySpec/RestClient.stats.swift
Until #142 is addressed, to avoid blocking the test suite.
=> Temporarily disable RestClientStats tests.

ablySpec/RestClient.swift
Force-unwrap with `!` instead. Otherwise, if the if-let fails to
unwrap the optional, it will be silently ignored. `!` crashes the
program at least, so that we know that we have something wrong
in the test code.
=> Don't use if-let to unwrap when it is sure that it will succeed.

ably-ios/ARTConnection.h, ably-ios/ARTRealtime.h, ably-ios/ARTRealtime.m, ablySpec/RealtimeClient.connection.swift, ablySpec/RealtimeClient.swift
RTN8a and RTN9a require them to be nullable.
=> Properly annotate ARTConnection.id, ARTConnection.key as optional.

ablySpec/Auth.swift
There is some abuse of ?-chaining in the test code. If we expect a
thing to be there and if not being that the case would mean that
test code (e. g. a helper) is wrong, force-unwrap should be used
instead of silently ignoring this condition with a ?-chain so that
the error is caught from the test framework. The test framework
should only tell us about the code being tested, not about the
code that tests the code being tested.
=> Replace ?-chains with force-unwraps.

ablySpec/Auth.swift, ablySpec/RealtimeClient.swift, ablySpec/RestClient.swift
This is more idiomatic, plus it forces the code to handle the else
case, plus avoids an additional level of indentation inside the
if-let.
=> Use guard-let instead of if-let, ?-chaining and force-unwrapping.

ably-iosTests/ARTRealtimeAttachTest.m
hasAttached was never being written. Also, now expectation is
fullfilled when the channel is closed so that the no-op
`[channel attach]` calls can have an observable effect if they're
wrong, ie. if they transition again to ATTACHED.
=> RTL4: Fix test that was doing nothing.

ablySpec/RestClient.channels.swift
As specified by [RSN3a](http://docs.ably.io/client-lib-development-guide/features/#RSN3a).
=> Test that getting the same channel name gives the same instance.

ablySpec/RealtimeClient.connection.swift
RTN4e wasn't testing what [the spec says](http://docs.ably.io/client-lib-development-guide/features/#RTN4e). What it was doing fits better in RTN4d.
=> Remove bad RTN4e test, merge with RTN4d.

ablySpec/Auth.swift
The test was left incomplete. It didn't check the GET query nor
the headers.
=> Actually test RSA8c1.

ably-ios/ARTRest.m, ablySpec/RestClient.swift
https://github.com/ably/docs/commit/b628023b83aca480464d55e4260e21ee20690d7a
Because the CI is currently pretty much useless, I'll leave this here:
=> RSC10, RSC14c: Adapt to new spec, 40140 -> [40140, 40150).

ably-ios/ARTChannel.h, ably-ios/ARTChannel.m, ably-ios/ARTPaginatedResult+Private.h, ably-ios/ARTPaginatedResult.h, ably-ios/ARTPresence.h, ably-ios/ARTPresence.m, ably-ios/ARTRealtime.h, ably-ios/ARTRealtime.m, ably-ios/ARTRealtimeChannel.h, ably-ios/ARTRealtimePresence.m, ably-ios/ARTRest.h, ably-ios/ARTRest.m, ably-ios/ARTRestPresence.m, ably-ios/ARTTypes.h
At first I thought this would help to write test code, as Xcode would help with autocomplete. Turns out that Swift ignores generics, except for Foundation collections. Anyway, it's done, and Objective-C clients can benefit from them.
=> Make ARTPaginatedResult generic.

ably-ios/ARTChannel.h, ably-ios/ARTLog.m, ably-ios/ARTPresenceMessage.m, ably-ios/ARTProtocolMessage.m, ably-ios/ARTRealtime.m, ably-ios/ARTRestChannel.m, ably-ios/ARTStatus.h, ably-ios/ARTStatus.m, ably-ios/ARTWebSocketTransport.m
Mostly about using NSInteger in formatted strings, which the compiler dislikes.
=> Fix compiler warnings.

ably-ios/ARTRealtime+Private.h, ably-ios/ARTRealtime.m, ably-iosTests/ARTRealtimeAttachTest.m, ably-iosTests/ARTRealtimeChannelTest.m, ably-iosTests/ARTRealtimeConnectTest.m, ably-iosTests/ARTRealtimeMessageTest.m, ably-iosTests/ARTRealtimePresenceTest.m, ably-iosTests/ARTRealtimeRecoverTest.m, ably-iosTests/ARTRealtimeResumeTest.m, ably-iosTests/ARTTestUtil.h, ably-iosTests/ARTTestUtil.m, ablySpec/RealtimeClient.connection.swift, ablySpec/RealtimeClient.swift, ablySpec/TestUtilities.swift
I was using `client.transition` to simulate _incomings of errors & connection state change_ and it is wrong because some of the logic is missed.
To change the connection states:
- `client.onConnected(message: ARTProtocolMessage)`
- `client.onDisconnected()`
- `client.onSuspended()`
- `client.onError(AblyTests.simulateError())`
With this PR we have:
- `simulateIncomingNormalClose`
- `simulateIncomingAbruptlyClose`
- `simulateIncomingError`
- `simulateLostConnection`
=> Test suite websocket

ablySpec/RestClient.swift
It's not working. Already marked in the sheet.
=> Mark "RestClient initializer should accept a token" as pending.

ably-ios/ARTConnection.h, ably-ios/ARTConnection.m, ably-ios/ARTEventEmitter+Private.h, ably-ios/ARTEventEmitter.h, ably-ios/ARTEventEmitter.m, ably-ios/ARTRealtime+Private.h, ably-ios/ARTRealtime.h, ably-ios/ARTRealtime.m, ably-ios/ARTRealtimeChannelSubscription.h, ably-ios/ARTRealtimeChannelSubscription.m, ably-ios/ARTTypes.h, ably-ios/ARTTypes.m, ably-iosTests/ARTRealtimeAttachTest.m, ably-iosTests/ARTRealtimeChannelTest.m, ably-iosTests/ARTRealtimeConnectTest.m, ably-iosTests/ARTRealtimeInitTest.m, ably-iosTests/ARTRealtimeMessageTest.m, ably-iosTests/ARTRealtimePresenceHistoryTest.m, ably-iosTests/ARTRealtimePresenceTest.m, ably-iosTests/ARTRealtimeRecoverTest.m, ably-iosTests/ARTRealtimeResumeTest.m, ably-iosTests/ARTTestUtil.m, ably.xcodeproj/project.pbxproj, ablySpec/Auth.swift, ablySpec/RealtimeClient.swift, ablySpec/RealtimeClientChannel.swift, ablySpec/RealtimeClientConnection.swift, ablySpec/TestUtilities.swift, ablySpec/Utilities.swift
Previously, ARTConnection managed state subscriptions and
ARTEventEmitter was just a shell. Now the heavy-lifting of
passing events around is done by ARTEventEmitter, which is
generic and can be reused by others, and ARTConnection just uses
it to emit events and expose its listening interface.
This also introduces ARTConnectionStateChange, used in connection
state events' callbacks, as the spec says.
Something that went away is that starting listening to events
dispatched the current event to the callback. Now it doesn't. It
starts listening to _changes_ from that point on. I think this
makes more sense and is consistent with what you expect from an
event emitter.
Fixes #133.
=> Rewrite ARTEventEmitter per the spec and adjust Connection.

ably-ios/ARTBaseMessage+Private.h, ably-ios/ARTBaseMessage.h, ably-ios/ARTBaseMessage.m, ably-ios/ARTChannel.m, ably-ios/ARTMessage.h, ably-ios/ARTRealtimeChannel.m, ably-ios/ARTRestChannel.m, ably-ios/ARTRestPresence.m, ably-ios/ably.modulemap, ably-iosTests/ARTRealtimeChannelHistoryTest.m, ably-iosTests/ARTRealtimeChannelTest.m, ably-iosTests/ARTRealtimeCryptoTest.m, ably-iosTests/ARTRealtimeMessageTest.m, ably-iosTests/ARTRealtimePresenceHistoryTest.m, ably-iosTests/ARTRealtimePresenceTest.m, ably-iosTests/ARTRealtimeRecoverTest.m, ably-iosTests/ARTRealtimeResumeTest.m, ably-iosTests/ARTRestChannelHistoryTest.m, ably-iosTests/ARTRestChannelPublishTest.m, ably-iosTests/ARTRestCryptoTest.m, ably-iosTests/ARTRestPresenceTest.m, ably.xcodeproj/project.pbxproj, ablySpec/RestChannel.swift
Plus, remove useless content method.
=> Separate BaseMessage private parts.

ably-ios/ARTConnectionDetails.h, ably-ios/ARTConnectionDetails.m, ably-ios/ARTJsonEncoder.m, ably-ios/ARTNSDictionary+ARTDictionaryUtil.h, ably-ios/ARTNSDictionary+ARTDictionaryUtil.m, ably-ios/ARTPaginatedResult.h, ably-ios/ARTPaginatedResult.m, ably-ios/ARTPresenceMessage.h, ably-ios/ARTPresenceMessage.m, ably-ios/ARTRealtime.h, ably-ios/ARTRealtime.m, ably-iosTests/ARTRealtimeChannelHistoryTest.m, ably-iosTests/ARTRestChannelHistoryTest.m, ablySpec/RestClientStats.swift
I think those aren't relevant enough to grant each its own pull request.
=> Minor changes to adjust to API spec.

ably-ios/ARTPaginatedResult.m
This behavior is consistent with [the spec](http://docs.ably.io/client-lib-development-guide/features/#TG4).
=> TG4: PaginatedResult.next calls back with nil if there's no next.

ably-ios/ARTRealtime.m, ably-ios/ARTRealtimeChannel.m, ably-iosTests/ARTRealtimeAttachTest.m, ablySpec/RealtimeClientChannel.swift
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/ably/ably-ios/221)
=> Fix RTL3a.

ably-ios/ARTRealtime+Private.h, ably-ios/ARTRealtime.m, ably-ios/ARTRealtimeChannel.m, ably-ios/ARTStatus.h, ablySpec/RealtimeClientChannel.swift
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/ably/ably-ios/226)
=> Fix RTL4f.

ably-ios/ARTConnection.m, ablySpec/RealtimeClientConnection.swift
The test was checking the connection serial before the connection
was established. The code behave correctly, but before CONNECTED
serial was 0 just because it's the default int value, then set to
-1 at CONNECTED. I've changed serial's initial value to -1, to
make it not important whether you check it before of after the
connection is established.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/ably/ably-ios/230)
=> Fix RTN10b.

ably-ios/ARTRealtimeChannel.m, ablySpec/RealtimeClientChannel.swift
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/ably/ably-ios/224)
=> Fix RTL4a.

ably-ios/ARTEventEmitter.h, ably-ios/ARTRealtimeChannel.h, ably-ios/ARTRealtimeChannel.m, ablySpec/RealtimeClientChannel.swift
Had to fix channel attach first. You can more easily review first one commit and then the other.
Fixes #220.
=> Fix attach callbacks, and add to RealtimeChannel.subscribe.

ably.xcodeproj/project.pbxproj, ablySpec/RestClientChannel.swift
Removed warnings:
```
objc[37154]: Class ARTRealtimeChannels is implemented in both Developer/Xcode/DerivedData/ably-gzdrbntzzqlpkifuyrtthlmrseij/Build/Products/Debug-iphonesimulator/Ably.framework/Ably and Developer/Xcode/DerivedData/ably-gzdrbntzzqlpkifuyrtthlmrseij/Build/Products/Debug-iphonesimulator/ablySpec.xctest/ablySpec. One of the two will be used. Which one is undefined.
objc[37154]: Class ARTRestChannels is implemented in both Developer/Xcode/DerivedData/ably-gzdrbntzzqlpkifuyrtthlmrseij/Build/Products/Debug-iphonesimulator/Ably.framework/Ably and Developer/Xcode/DerivedData/ably-gzdrbntzzqlpkifuyrtthlmrseij/Build/Products/Debug-iphonesimulator/ablySpec.xctest/ablySpec. One of the two will be used. Which one is undefined.
objc[37154]: Class ARTDataEncoderOutput is implemented …
```
=> Test suite enhancements

ably-ios/ARTChannel.h, ably-ios/ARTChannel.m, ably-ios/ARTRealtimeChannel.h, ably-ios/ARTRealtimeChannel.m, ably-iosTests/ARTReadmeExamples.m, ably-iosTests/ARTRealtimeChannelHistoryTest.m, ably-iosTests/ARTRealtimeCryptoTest.m, ably-iosTests/ARTRealtimeMessageTest.m, ably-iosTests/ARTRestChannelPublishTest.m, ably-iosTests/ARTRestCryptoTest.m, ablySpec/ReadmeExamples.swift, ablySpec/RealtimeClientChannel.swift, ablySpec/RestClientChannel.swift
I notice this problem from the README examples.
=> History request without a query shouldn't throw errors

ably-ios/ARTRealtimeChannel+Private.h, ably-ios/ARTRealtimeChannel.m, ably-ios/ARTRealtimeChannels.h, ably-ios/ARTRealtimeChannels.m, ably-iosTests/ARTRealtimeAttachTest.m, ably-iosTests/ARTRealtimeChannelTest.m, ablySpec/RealtimeClientChannel.swift
Just removing the channel from the channels collection isn't
enough; the channel might have references elsewehere, including
reference cycles if the listener/subscriber callbacks close over
it.
=> Force full channel release.

ably-ios/ARTConnection+Private.h, ably-ios/ARTConnection.h, ably-ios/ARTConnection.m, ably-ios/ARTRealtime.m
Internally we still need to wrap the raw enum values in NSNumber,
but that shouldn't be exposed.
=> Connection EventEmitter: use enum instead of NSNumber as event type.

ably-ios/ARTClientOptions.m, ably-ios/ARTRealtime.m, ably-ios/ARTRealtimeChannel.m, ably-ios/ARTWebSocketTransport.h, ably-ios/ARTWebSocketTransport.m, ablySpec/RealtimeClientChannel.swift, ablySpec/RealtimeClientConnection.swift, ablySpec/TestUtilities.swift
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/ably/ably-ios/228)
=> Fix RTN7c: notify publish callbacks of broken connection.

ably-ios/ARTDataQuery+Private.h, ably-ios/ARTDataQuery.m, ably-ios/ARTRealtimeChannel.m, ablySpec/RealtimeClientChannel.swift
=> RTL10b: Implement untilAttach for RealtimeChannel.history.

ably-ios/ARTChannel.h, ably-ios/ARTPresence.h, ably-ios/ARTPresence.m, ably-ios/ARTRealtime.h, ably-ios/ARTRealtime.m, ably-ios/ARTRealtimeChannel.h, ably-ios/ARTRealtimePresence.h, ably-ios/ARTRealtimePresence.m, ably-ios/ARTRest.h, ably-ios/ARTRest.m, ably-ios/ARTRestPresence.m, ably-iosTests/ARTRealtimePresenceHistoryTest.m, ably-iosTests/ARTRestPresenceTest.m, ablySpec/RealtimeClient.swift, ablySpec/RestClientStats.swift
We changed `Channel.history`, but left `Presence.history` and `stats` behind.
=> Uniformize stats and history interfaces.

ably-ios/ARTTokenParams.h, ably-ios/ARTTokenParams.m, ablySpec/Auth.swift
=> TokenParams.timestamp: use current at getter, not at constructor.

ably-ios/ARTChannel.h, ably-ios/ARTChannel.m, ably-ios/ARTChannelOptions.h, ably-ios/ARTChannelOptions.m, ably-ios/ARTCrypto+Private.h, ably-ios/ARTCrypto.h, ably-ios/ARTCrypto.m, ably-ios/ARTDataEncoder.m, ably-ios/Ably.modulemap, ably-iosTests/ARTRealtimeChannelTest.m, ably-iosTests/ARTRealtimeCryptoTest.m, ably-iosTests/ARTRestCryptoTest.m, ably-iosTests/ARTTestUtil.h, ably-iosTests/ARTTestUtil.m, ably.xcodeproj/project.pbxproj, ablySpec/Crypto.swift, ablySpec/RealtimeClientChannel.swift, ablySpec/RestClientChannel.swift, ablySpec/RestClientChannels.swift, ablySpec/ablySpec-Bridging-Header.h
https://github.com/ably/ably-ios/pull/211#discussion_r53042652
I've kept the IV param in Crypto.getDefaultParams for the reasons mentioned in the discussion.
=> Adjust Crypto, CipherParams and ChannelOptions to spec.

ably-ios/ARTRealtimeChannel.m, ably-ios/ARTStatus.h, ablySpec/RealtimeClientChannel.swift
=> Test RTL5*.

.travis.yml
#143 - Use `travis_wait` when a long running command or compile step regularly takes longer than 10 minutes without producing any output. It writes a short line to the build log every minute for 20 minutes, extending the amount of time your command has to finish.
=> Travis: fix stalled build

Source/ARTAuth.h, Source/ARTAuth.m, Source/ARTAuthOptions.h, Source/ARTConnection.m, Source/ARTHttp.h, Source/ARTHttp.m, Source/ARTPaginatedResult+Private.h, Source/ARTPaginatedResult.h, Source/ARTPaginatedResult.m, Source/ARTQueuedMessage.h, Source/ARTQueuedMessage.m, Source/ARTRealtime+Private.h, Source/ARTRealtime.h, Source/ARTRealtime.m, Source/ARTRealtimeChannel+Private.h, Source/ARTRealtimeChannel.m, Source/ARTRest+Private.h, Source/ARTRest.h, Source/ARTRest.m, Source/ARTTypes.h, Source/ARTURLSessionServerTrust.h, Source/ARTURLSessionServerTrust.m, Spec/RestClientStats.swift, Spec/TestUtilities.swift, Tests/ARTRealtimePresenceHistoryTest.m
Typedefs for block types are pretty annoying, because when checking how you should call some method that takes a callback you then need also to check the signature of the callback type. Now it's all inlined and explicit, if more verbose.
=> Remove block typedefs, use block syntax explicitly.

Source/ARTRealtime.m, Source/ARTRealtimeChannel.m, Source/ARTRest.m, Source/ARTTypes.h, Spec/RealtimeClientChannel.swift, Tests/ARTRealtimePresenceTest.m
See discussion in https://github.com/ably/wiki/issues/68
blind whole-repo `s/nitialis/nitializ/`' - haven't tested this (don't know how and don't think I can on a non-mac), so please test before merging
=> Standardise on initialized

Source/ARTHttp.m, Tests/ARTTestUtil.m
- should always enqueue the callback block
=> Fix uncaught HTTP exception

Source/ARTDataQuery.m
"Realtime" was incorrectly spelled as "Realitme"
=> Fix typo in ARTDataQuery.m

Tests/ARTFallbackTest.m, Tests/ARTHttpTest.m, Tests/ARTReadmeExamples.m, Tests/ARTRealtimeAttachTest.m, Tests/ARTRealtimeChannelHistoryTest.m, Tests/ARTRealtimeChannelTest.m, Tests/ARTRealtimeConnectTest.m, Tests/ARTRealtimeCryptoTest.m, Tests/ARTRealtimeInitTest.m, Tests/ARTRealtimeMessageTest.m, Tests/ARTRealtimePresenceHistoryTest.m, Tests/ARTRealtimePresenceTest.m, Tests/ARTRealtimeRecoverTest.m, Tests/ARTRealtimeResumeTest.m, Tests/ARTRestCapabilityTest.m, Tests/ARTRestChannelHistoryTest.m, Tests/ARTRestChannelPublishTest.m, Tests/ARTRestCryptoTest.m, Tests/ARTRestInitTest.m, Tests/ARTRestPresenceTest.m, Tests/ARTRestTokenTest.m, Tests/ARTTestUtil.h, Tests/ARTTestUtil.m
I declared each expectation variable as `__weak` to avoid API violations. The expectation will be released when the timeout expires. So if the task takes longer than the timeout, the expectation variable will be nil when the task completion handler is called. Thus the `fulfill` method will be called on nil, doing nothing.
=> Test suite: avoid calling the `fulfill` after the wait context has ended

Spec/Auth.swift
`TokenParams__timestamp__if_not_explicitly_set__should_be_generated_at_the_getter_and_stick, failed - expected to be close to <1458091169459.0000> (within 1.0000), got <1458091169460.0000>`
=> Fix: expect timestamp with higher delta

Spec/RealtimeClientChannel.swift, Spec/RealtimeClientPresence.swift
Before we were subscribing the presence listener and entering in
parallel connections, it was possible that the latter finished
before the former attached, thus missing the event.
=> RTP8a, RTL7f: attach first to avoid race condition.

Ably.xcodeproj/project.pbxproj, Source/ARTChannel.h, Source/ARTChannel.m, Source/ARTClientOptions.m, Source/ARTPresence+Private.h, Source/ARTPresence.h, Source/ARTPresence.m, Source/ARTRealtimeChannel+Private.h, Source/ARTRealtimeChannel.h, Source/ARTRealtimeChannel.m, Source/ARTRealtimePresence+Private.h, Source/ARTRealtimePresence.h, Source/ARTRealtimePresence.m, Source/ARTRestChannel+Private.h, Source/ARTRestChannel.h, Source/ARTRestChannel.m, Source/ARTRestChannels.m, Source/ARTRestPresence+Private.h, Source/ARTRestPresence.h, Source/ARTRestPresence.m, Spec/RealtimeClientChannel.swift, Spec/RealtimeClientConnection.swift, Spec/RestClientChannel.swift, Spec/RestClientPresence.swift, Tests/ARTRestChannelHistoryTest.m, Tests/ARTRestChannelPublishTest.m
Previously, we had some situations in which, for convenience, we were
inheriting rather than composing (RealtimeChannel inheriting from
RestChannel). This was causing problems in places where some parent
class implemented `method:(A)a` while a child class was implementing
`method:(B)b`. Swift 2.2 doesn't let you do this, so it's necessary for
that, but it's also a good idea for Swift <2.2 if only for code
organization and soundness.
Also added some changes in the test Swift code for forwards 
compatibility.
=> Rearrange types relationships to avoid ambiguities.

.travis.yml, Ably.xcodeproj/project.pbxproj, Podfile, Podfile.lock, README.md, Spec/Auth.swift, Spec/RealtimeClientChannel.swift, Spec/RealtimeClientPresence.swift, Spec/RestClientChannels.swift, Spec/RestClientPresence.swift
WIP to check via Travis if it's backwards compatible. If it isn't we need to figure out how/if we're going to maintain two versions.
=> Adapt to Swift 2.2

Tests/ARTRealtimeAttachTest.m, Tests/ARTRealtimeChannelHistoryTest.m, Tests/ARTRealtimeChannelTest.m, Tests/ARTRealtimeConnectTest.m, Tests/ARTRealtimeCryptoTest.m, Tests/ARTRealtimeInitTest.m, Tests/ARTRealtimeMessageTest.m, Tests/ARTRealtimePresenceHistoryTest.m, Tests/ARTRealtimePresenceTest.m, Tests/ARTRealtimeRecoverTest.m, Tests/ARTRealtimeResumeTest.m, Tests/ARTRestCapabilityTest.m, Tests/ARTRestChannelHistoryTest.m, Tests/ARTRestChannelPublishTest.m, Tests/ARTRestCryptoTest.m, Tests/ARTRestInitTest.m, Tests/ARTRestPresenceTest.m, Tests/ARTRestTokenTest.m, Tests/ARTTestUtil.h, Tests/ARTTestUtil.m
`XCTestExpectation` was created before the `https://sandbox-rest.ably.io:443/apps` request and the timeout was easily exceeded.
=> Legacy tests: Sandbox ClientOptions

Source/ARTChannels+Private.h, Source/ARTChannels.m, Source/ARTRealtimeChannels.m, Source/ARTRest+Private.h, Source/ARTRest.m, Spec/RealtimeClientChannel.swift, Spec/RealtimeClientChannels.swift, Spec/RealtimeClientConnection.swift, Spec/RestClientChannel.swift, Spec/RestClientChannels.swift, Spec/RestClientStats.swift, Spec/TestUtilities.swift, Tests/ARTRealtimeChannelTest.m, Tests/ARTRestCapabilityTest.m, Tests/ARTRestPresenceTest.m, Tests/ARTTestUtil.m
For this, we isolate tests by prepending a prefix to channel names in
different tests (ie. that use different calls to 
TestUtilties.setupOptions.)
This should make #397 unnecessary.
=> Test suites: reuse test app.

Source/ARTConnection.m, Source/ARTEventEmitter.h, Source/ARTEventEmitter.m, Source/ARTRealtime+Private.h, Source/ARTRealtime.m, Source/ARTRealtimeChannel.m, Spec/RealtimeClientChannel.swift, Spec/RealtimeClientConnection.swift, Spec/RealtimeClientPresence.swift, Spec/TestUtilities.swift, Spec/Utilities.swift, Tests/ARTRealtimeAttachTest.m
This is required by #385. Note that ably/docs#112 is not merged yet.
Split in several commits for ease of consumption.
=> Conform to spec changes at ably/docs#112.

Tests/ARTTestUtil.m
In the Obj-C test suite, ARTReadmeExamples are being before any other
test that uses setupApp. Because tests in ARTReadmeExamples don't have
any assertions, they are not serialized, ie. we don't really wait for
them to finish before running the next test. This causes each one of
them to create a separate setupApp, and this can cause a race condition
when the first "real" test starts (ARTRealtimeAttachTest.testAttachedChannelFails)
in which a new test app arrives in the middle of its execution, which
causes it to use two separate test channel name prefixes (because the
global ARTChannels_getChannelNamePrefix is reassigned) and failing.
It's a bit tricky and definitely hacky.
This waits for the first test app to be created to avoid creating more
than one, and so that the situation explained …
=> Fix race condition when calling ARTTestUtil.setupApp.

Source/ARTAuth.m, Spec/Auth.swift
We were using basic authentication when calling /requestToken, which
of course only works if you have a key, which is not supposed to be
the case.
An existing test has been modified to test this.
=> Don't use auth when requesting tokens.

Source/ARTDataEncoder.m, Spec/RealtimeClientConnection.swift, Spec/RestClientChannel.swift, Spec/TestUtilities.swift
Previously, we were just inlining it:
"messages": [{"data": {"foo": "bar"}}]
What the JS library expects, and really what [RSL4d3](http://docs.ably.io/client-lib-development-guide/features/#RSL4d3) says:
"messages": [{"data": "{\"foo\": \"bar\"}"}]
So now we do that.
=> Encode JSON message data as string.

README.md
#461 
For preliminary review, if everything is OK I'll provide an `ObjectiveC` snippet.
=> Swift snippet using the authCallback.

Spec/RestClient.swift
Fix for https://github.com/ably/ably-ios/pull/473/files/2d05f1bdffb5587cdd006a7e0ebefd158c67c8fb#r77165419
=> Fix RSC11: ignore environment when host is customized

Source/ARTAuth.m, Source/ARTDataQuery.m, Source/ARTEncoder.h, Source/ARTJsonLikeEncoder.m, Source/ARTTokenParams.m, Source/ARTTypes.h, Source/ARTTypes.m, Spec/Auth.swift
=> Fix RSA8c: check authUrl content expectations

Source/ARTRealtime.m, Spec/RealtimeClientConnection.swift
Please review and merge if everything looks good.
=> RTN17b as a part of 0.9

Ably.xcodeproj/project.pbxproj, Source/ARTAuth.m, Source/ARTRestPresence.m, Source/ARTStatus.h, Spec/Auth.swift, Spec/RealtimeClient.swift, Spec/RealtimeClientChannel.swift, Spec/RealtimeClientChannels.swift, Spec/RealtimeClientConnection.swift, Spec/RealtimeClientPresence.swift, Spec/RestClient.swift, Spec/RestClientChannel.swift, Spec/RestClientPresence.swift, Tests/ARTRealtime+TestSuite.h, Tests/ARTRealtime+TestSuite.m, Tests/ARTRealtimeAttachTest.m, Tests/ARTRealtimeInitTest.m, Tests/ARTRealtimeMessageTest.m, Tests/ARTRealtimePresenceHistoryTest.m, Tests/ARTRealtimePresenceTest.m, Tests/ARTRealtimeRecoverTest.m, Tests/ARTRealtimeResumeTest.m, Tests/ARTTestUtil.h, Tests/ARTTestUtil.m
[Executed 541 tests, with 0 failures (0 unexpected) in 246.092 (247.119) seconds](https://travis-ci.org/ably/ably-ios/builds/161359752#L1561)
Merge this before #505.
=> Fix spec failures

Ably.xcodeproj/project.pbxproj, Source/ARTAuth.m, Source/ARTRestPresence.m, Source/ARTStatus.h, Spec/Auth.swift, Spec/RealtimeClient.swift, Spec/RealtimeClientChannel.swift, Spec/RealtimeClientChannels.swift, Spec/RealtimeClientConnection.swift, Spec/RealtimeClientPresence.swift, Spec/RestClient.swift, Spec/RestClientChannel.swift, Spec/RestClientPresence.swift, Tests/ARTRealtime+TestSuite.h, Tests/ARTRealtime+TestSuite.m, Tests/ARTRealtimeAttachTest.m, Tests/ARTRealtimeInitTest.m, Tests/ARTRealtimeMessageTest.m, Tests/ARTRealtimePresenceHistoryTest.m, Tests/ARTRealtimePresenceTest.m, Tests/ARTRealtimeRecoverTest.m, Tests/ARTRealtimeResumeTest.m, Tests/ARTTestUtil.h, Tests/ARTTestUtil.m
[Executed 157 tests, with 0 failures (0 unexpected) in 108.130 (108.468) seconds](https://travis-ci.org/ably/ably-ios/builds/161103426#L1001)
=> Fix legacy tests: account blocked (connection limits exceeded)

Source/ARTRealtimeChannel.m, Source/ARTRealtimePresence.m, Spec/RealtimeClientChannel.swift, Spec/RealtimeClientPresence.swift
#485 
> (RTL4g) If the channel is in the FAILED state, the attach request sets its errorReason to null, and proceeds with a channel attach described in RTL4b, RTL4h and RTL4c
Please only merge if all tests are passing.
This can break other tests like `RTP11b`.
=> Fix: should attach if the channel is in the FAILED state

Ably.podspec, Examples/Tests/Podfile.lock, README.md, Source/ARTDefault.h, Source/ARTDefault.m, Source/Info.plist, Spec/RealtimeClient.swift, Spec/RealtimeClientConnection.swift, Spec/RestClient.swift
> If an array of custom fallback hosts are provided in @ClientOptions#fallbackHosts@, then they will be used instead.
Already implemented.
> If an empty array of fallback hosts is provided, then fallback host functionality is disabled
Already implemented.
=> Update RSC15a for 0.9

Source/ARTNSDate+ARTUtil.h, Source/ARTNSDate+ARTUtil.m
We were converting timestamps to NSInteger, which is a 32-bit or 64-bit
int depending on the architecture. `long long` is guaranteed to be
64-bit wide.
Fixes #525.
=> Fix timestamp decoding for 32-bit architectures.

Source/ARTDefault.m
It's not available when the library is used from another bundle.
Fixes #530.
=> Don't read library version from bundle.

Ably.xcodeproj/project.pbxproj, Source/ARTAuth.m, Source/ARTGCD.h, Source/ARTGCD.m, Source/ARTRest+Private.h, Source/ARTRest.m
#531
- interacting with certain frameworks like UIKit, we need to ensure that all calls happen from the main thread.
=> Fix: check if authCallback is running on a background queue

Source/ARTRealtime.m, Source/ARTRealtimeChannel.m, Spec/RealtimeClientConnection.swift, Spec/TestUtilities.swift
=> Fix: connection resume does not fire channel detached

Spec/RealtimeClientPresence.swift, Spec/RestClientPresence.swift, Spec/TestUtilities.swift
This was killing me. This is fixed on Swift v3.0 but since we are still using v2.2 I decided to change the code because Xcode is taking ~7 seconds indexing.
=> Swift performance: speed up code completion

Examples/Tests/TestsTests/TestsTests.swift, Source/ARTConnection.m, Source/ARTDefault.m, Source/ARTEventEmitter.h, Source/ARTEventEmitter.m, Source/ARTHttp.h, Source/ARTHttp.m, Source/ARTPresenceMap.h, Source/ARTPresenceMap.m, Source/ARTRealtime.m, Source/ARTRealtimeChannel.m, Source/ARTWebSocketTransport+Private.h, Source/ARTWebSocketTransport.m, Spec/RealtimeClient.swift, Spec/RealtimeClientChannel.swift, Spec/RealtimeClientConnection.swift, Spec/RealtimeClientPresence.swift, Spec/RestClient.swift, Spec/RestClientPresence.swift
It wasn't firing transport events when the Realtime object was created on a background queue.
UPDATE: Rest was with the same problem.
=> Fix: Realtime transport should fire events on a serial queue

Source/ARTAuth.m, Source/ARTBaseMessage.m, Source/ARTChannel+Private.h, Source/ARTChannel.m, Source/ARTEncoder.h, Source/ARTJsonEncoder.m, Source/ARTJsonLikeEncoder.h, Source/ARTJsonLikeEncoder.m, Source/ARTMsgpackEncoder.m, Source/ARTPaginatedResult+Private.h, Source/ARTPaginatedResult.m, Source/ARTRealtime.m, Source/ARTRealtimeChannel.m, Source/ARTRealtimeTransport.h, Source/ARTRest.m, Source/ARTRestChannel.m, Source/ARTRestPresence.m, Source/ARTStatus.h, Source/ARTStatus.m, Source/ARTWebSocketTransport+Private.h, Source/ARTWebSocketTransport.m, Spec/Auth.swift, Spec/RealtimeClientChannel.swift, Spec/RealtimeClientPresence.swift, Spec/RestClientChannel.swift, Spec/Stats.swift, Spec/TestUtilities.swift, Spec/Utilities.swift
=> Encoder: handle invalid types gracefully

Source/ARTLog+Private.h, Source/ARTLog.m, Spec/Utilities.swift
=> Log history

Ably.podspec, Ably.xcodeproj/project.pbxproj, Podfile, Podfile.lock, Source/ARTWebSocketTransport.m, Spec/Auth.swift, Spec/Crypto.swift, Spec/Helpers.swift, Spec/NSObject+TestSuite.swift, Spec/ReadmeExamples.swift, Spec/RealtimeClient.swift, Spec/RealtimeClientChannel.swift, Spec/RealtimeClientChannels.swift, Spec/RealtimeClientConnection.swift, Spec/RealtimeClientPresence.swift, Spec/RestClient.swift, Spec/RestClientChannel.swift, Spec/RestClientChannels.swift, Spec/RestClientPresence.swift, Spec/RestClientStats.swift, Spec/Stats.swift, Spec/TestUtilities.swift, Spec/Utilities.swift
New versions of Xcode can't compile Swift 2, so I couldn't run the
test suite anymore.
=> Convert to Swift 3.

Source/ARTJsonLikeEncoder.m, Source/ARTTokenParams.h, Source/ARTTokenParams.m, Source/ARTTokenRequest.h, Source/ARTTokenRequest.m, Spec/Auth.swift, Spec/RealtimeClientConnection.swift, Spec/RestClient.swift, Spec/TestUtilities.swift
Fixes #618.
Part of ably/docs#303.
=> Default token TTL to nil, not 60*60.

Source/ARTRealtime.m, Spec/RealtimeClient.swift, Spec/RealtimeClientConnection.swift
Fixes #622.
The test suite has a few broken tests. I don't think they're caused by
this change, although I haven't checked. We probably should take a
deeper look at them before doing a release.
=> Reuse connection when receiving an AUTH.

Source/ARTPresenceMap.h, Source/ARTRealtimePresence.m, Spec/RealtimeClientPresence.swift
=> Implement RTP11d.

Source/ARTPresenceMap.m, Source/ARTRealtimePresence.m, Spec/RealtimeClientPresence.swift
=> Fix: presence map key and get with query (clientId and connectionId)

Source/ARTRealtime.m, Source/ARTWebSocketTransport.m, Spec/RealtimeClient.swift
=> Move to DISCONNECTED on unexpected WebSocket close.

Ably.xcodeproj/project.pbxproj, Examples/Tests/Podfile, Examples/Tests/Podfile.lock, Examples/Tests/Tests.xcodeproj/project.pbxproj, Examples/Tests/TestsTests/TestsTests.swift, Source/ARTClientOptions.h, Source/ARTClientOptions.m, Source/ARTDeviceDetails.m, Source/ARTDevicePushDetails.m, Source/ARTJsonLikeEncoder.m, Source/ARTPush.h, Source/ARTPush.m, Source/ARTPushAdmin.h, Source/ARTPushAdmin.m, Source/ARTPushChannel.m, Source/ARTPushChannelSubscription.m, Source/ARTPushChannelSubscriptions.m, Source/ARTPushDeviceRegistrations.h, Source/ARTPushDeviceRegistrations.m, Source/ARTRest.m, Source/ARTStatus.h, Source/ARTStatus.m, Source/ARTTypes.h, Source/ARTTypes.m, Source/ARTURLSessionServerTrust.m, Spec/PushAdmin.swift, Spec/TestUtilities.swift
It doesn't compile:
The Push implementation is missing some methods.
=> Push Admin tests

Source/ARTPushActivationStateMachine.m, Source/ARTRest.h, Source/ARTRest.m
=> Push: fix deadlock in rest.device

Ably.xcodeproj/project.pbxproj
=> Remove warning about Swift @objc inference

README.md
=> Add supported platform to README

Source/ARTLog.m, Source/ARTNSDate+ARTUtil.m, Spec/Utilities.swift
=> Fix memory consumption bug

Spec/RealtimeClient.swift
While trying to reproduce an [issue with the JS SDK](https://github.com/ably/ably-js/issues/450) I ended up writing a test for the sequence of received messages.
=> Add test for sequence of received messages

Source/ARTRealtime.m, Spec/RealtimeClientConnection.swift
Enforces a new connection when the last activity is > than `(_maxIdleInterval + _connectionStateTtl)`
Mimics [this behavior in JS](https://github.com/ably/ably-js/blob/c55b4518d6f096e4bde90afcd04c5ba35d466f3c/common/lib/transport/connectionmanager.js#L702-L712), called when [a connection gets started](https://github.com/ably/ably-js/blob/master/common/lib/transport/connectionmanager.js#L1039).
cc @paddybyers
=> Enforce new connection when last activity > than (idle interval + TTL)

Spec/PushAdmin.swift
Channel subscriptions started before all the devices were successfully registered
=> Fix race condition in preparing tests for push

Source/ARTAuth.m, Source/ARTRealtime.m, Spec/Auth.swift, Spec/RealtimeClientConnection.swift, Spec/TestUtilities.swift
=> Add jwt tests

.travis.yml, Spec/Info.plist, Spec/RealtimeClient.swift, Spec/RestClient.swift, Spec/TestUtilities.swift, fastlane/Fastfile
This allows running tests like
`export ABLY_ENV=push-dev-deployment; fastlane test_iOS11`
=> Add ABLY_ENV support

Source/ARTRest.m
Sending both mime types, e.g. `accept: 'application/json,application/x-msgpack'` confuses realtime, which might return responses with `Content-type: application/json` even when the request was made with `Content-type: application/x-msgpack`
=> Set the Accept http header to the mime type of the selected encoder

Source/ARTRest.m, Spec/RealtimeClientChannel.swift
```
(TM2a) id string – unique ID for this message. This attribute is always populated for messages received over REST. For messages received over Realtime, if the message does not contain an id, it should be set to protocolMsgId:index, where protocolMsgId is the id of the ProtocolMessage encapsulating it, and index is the index of the message inside the messages array of the ProtocolMessage
```
=> Add test for TM2a

Spec/Utilities.swift
`(RTE6a) The set of listeners called by emit must not change over the course of the emit. That is: If a listener being called by emit registers another listener, that second listener should not be called by that invocation of emit (even if it would have been called had it already been present); and if a listener being called by emit removes other listeners, but those other listeners would otherwise have been called during that emit invocation, they should still be called. Tests should exist for both adding and removing. See https://goo.gl/OVTtjO`
=> Add test for RTE6a

Source/ARTRealtime.m, Spec/RealtimeClientConnection.swift
`(RTN15h2) If the DISCONNECTED message contains a token error (statusCode value of 401 and error code value in the range 40140 <= code < 40150) and the library has the means to renew the token, a single attempt to create a new token should be made and a new connection attempt initiated using the new token. If the token creation fails or the next connection attempt fails due to a token error, the connection will transition to the DISCONNECTED state and the Connection#errorReason will be set.`
While working on this I got a bunch of failures related to presence. Addressed here: https://github.com/ably/ably-ios/pull/751
=> Add rtn15h2

Source/ARTRealtime.m, Source/ARTRest.m, Spec/Auth.swift, Spec/RealtimeClientConnection.swift, Spec/RestClientChannel.swift
This: 
- fixes the [implementation of RTN15h2](https://github.com/ably/ably-ios/commit/9f984a2e1063c9f0489e61ead13a7cb2d11fef01)
- fixed test regressions related to the addition of RTN15h2
- [fixes](https://github.com/ably/ably-ios/commit/4ff2639bf9434b021cc1a8467d6b4fc2ed272396) a bug introduced in a [previous PR](https://github.com/ably/ably-ios/pull/743) about the values passed in the `Accept` header
=> Fix failing tests

Source/ARTBaseMessage.h, Source/ARTBaseMessage.m, Source/ARTChannel.h, Source/ARTChannel.m, Source/ARTConnection+Private.h, Source/ARTConnection.h, Source/ARTConnection.m, Source/ARTMessage.h, Source/ARTMessage.m, Source/ARTRealtime.m, Source/ARTRealtimeChannel.m, Source/ARTTypes.h, Source/ARTTypes.m, Spec/RealtimeClient.swift, Spec/RestClient.swift, Spec/TestUtilities.swift, Spec/Utilities.swift
This addresses spec `TO3l8*` and `RSL1i` items, aka throw an error before publishing messages when the size exceeds `maxMessageSize`.
NOTE: queued messages exceeding `maxMessageSize` (`RTL6d1`) will be addressed in a separate PR
=> Add max message size

Source/ARTBaseMessage.h, Source/ARTBaseMessage.m, Source/ARTMessage.h, Source/ARTMessage.m
So that a presence message doesn't inherit the `name` property
Fix #762
=> Move name property to ARTMessage

Source/ARTRealtime+Private.h, Source/ARTRealtime.m, Spec/RealtimeClient.swift, Spec/RealtimeClientChannel.swift, Spec/RealtimeClientConnection.swift, Spec/RealtimeClientPresence.swift
`(RTN15a) If a Connection transport is disconnected unexpectedly or if a token expires, then the Connection manager will immediately attempt to reconnect and restore the connection state. Connection state recovery is provided by the Ably service and ensures that whilst the client is disconnected, all events are queued and channel state is retained on the Ably servers. When a new connection is made with the correct connection recovery key, the client is able to catch up by receiving the queued ProtocolMessages from Ably.`
- Includes cleanup of tests that were tweaking the value of `disconnectedRetryTimeout`
- adds a private `suspendImmediateReconnection` property to prevent an immediate reconnection after a disconnection happens. Handy for tests.
=> Add RTN15a

Spec/Auth.swift, Spec/RealtimeClient.swift, Spec/RealtimeClientConnection.swift, Spec/RestClient.swift
=> NSURL -> URL in Swift code

Spec/RealtimeClientConnection.swift
=> Add test for RTN15h1

Source/ARTProtocolMessage.m, Spec/RealtimeClientChannel.swift
Adds `RTL6d1`
```
(RTL6d) Messages for a single channel that have been queued may be sent in a single ProtocolMessage by bundling them into the ProtocolMessage#messages array, subject to the following constraints:
(RTL6d1) The resulting ProtocolMesssage must not exceed the maxMessageSize
```
=> Add rtl6d1

Ably.xcodeproj/project.pbxproj, Source/ARTNSString+ARTUtil.h, Source/ARTNSString+ARTUtil.m, Source/ARTProtocolMessage.m, Spec/RealtimeClientChannel.swift
`(RTL6d2) Messages with differing clientId values must not be bundled together. (Note that this constraint only applies to what the client library can autonomously do as part of queuing messages, not to what the user can do by publishing an array of Messages. It exists because if any Message in a ProtocolMessage has an invalid clientId, the entire ProtocolMessage is rejected. This is fine if the user has deliberately published the Messages together – they requested atomicity – but not if the client library has bundled them without the user's knowledge)`
=> Add RTL6d2

Spec/Auth.swift
Realtime clients outside the `it` method scope will be executed anyway if you run an unrelated and specific spec. This can confuse the developer when it’s debugging some Realtime code while expecting a specific behaviour but something else happens.
For example, while debugging an issue and running only one test by using the `fit` function, I expected 1 initialisation of ARTRealtime and I got 6!
Related with #758.
=> Fix Realtime clients creation outside the `it` method scope

.travis.yml, Podfile, Podfile.lock, Spec/RealtimeClientConnection.swift, Spec/RestClientChannel.swift, Spec/TestUtilities.swift
Can't use Xcode 9 to run tests anymore 😩 The [_Could not attach to pid_](https://stackoverflow.com/questions/44651029/xcode-9-could-not-attach-to-pid) is ruining my day. I tried many things and nothing fixed it.
But I can run tests using in Xcode 10 🤷‍♂️ So I did just the minimal changes to be able to work with Xcode 10.
@funkyboy Could you use this in your `xcode10-ios12-swift42` branch? Sorry, I tried to use yours but you have so many changes that I preferred to create mine with little changes.
=> Xcode 10 minimal support

fastlane/Fastfile
Now that we've disabled the Slack webhooks for every iOS build on every platform, the builds need to also stop attempting to notify Slack.
@ricardopereira I assume we still see the results of Fastlane in the build output itself so this change is fine?
=> Stop notifying Slack for every platform and every iOS build

README.md
Ahead of 1.1 release, we'll be informing users about the features that aren't currently supported by this library.
=> Known Limitations section in README [WIP]

Source/ARTConstants.m, Source/ARTHTTPPaginatedResponse+Private.h, Source/ARTHTTPPaginatedResponse.h, Source/ARTHTTPPaginatedResponse.m, Source/ARTHttp.m, Source/ARTRealtime.m, Source/ARTRealtimeChannel.m, Source/ARTRest.m, Spec/RealtimeClientConnection.swift, Spec/RestClient.swift, Spec/TestUtilities.swift
=> Fix Channel.subscribe onAttachCallback

Source/ARTPushActivationState.m, Source/ARTRealtimeChannel.m, Spec/PushActivationStateMachine.swift
> (RSH3e) State WaitingForRegistrationUpdate:
>  * (RSH3e2) On event RegistrationUpdated:
>    * ([RSH3e2a](https://docs.ably.io/client-lib-development-guide/features/#RSH3e2a)) Transitions to WaitingForNewPushDeviceDetails.
Related with #863
=> Fix Push Activation State Machine: WaitingForRegistrationUpdate bad state

Source/ARTAuth.m, Spec/Auth.swift
https://travis-ci.org/ably/ably-cocoa/jobs/552920920#L2002
Example of test that was failing: https://github.com/ably/ably-cocoa/blob/0054046ea315741b0124461f6404b48d6384e530/Spec/Auth.swift#L1488
Discussed with Simon:
> @ricardopereira The bug is that you aren't properly URI-encoding the token request when sending it as a QS param to the echo server. In particular, `+`s appear to not be being uri-encoded; they should be encoded to `%2B`.
(So you're getting the result back and the literal pluses are intrepreted as spaces in the url, so you're getting a mac of  `h5qZ BFGbbcPc /llzOLracCqBgsz/g94KtJgoiYUE=` when it should be `+h5qZ+BFGbbcPc+/llzOLracCqBgsz/g94KtJgoiYUE=`)
=> Tests using `echo.ably.io` were failing intermittently with "Request mac does not match"

Source/ARTAuth+Private.h, Source/ARTAuth.m, Source/ARTHttp.h, Source/ARTHttp.m, Source/ARTRealtime+Private.h, Source/ARTRealtime.m, Source/ARTRealtimeTransport.h, Source/ARTRest+Private.h, Source/ARTRest.m, Source/ARTTypes.h, Source/ARTURLSessionServerTrust.h, Source/ARTURLSessionServerTrust.m, Source/ARTWebSocketTransport+Private.h, Source/ARTWebSocketTransport.m, Spec/Auth.swift, Spec/RealtimeClient.swift, Spec/RealtimeClientConnection.swift, Spec/TestUtilities.swift
I noticed this issue while testing the Push Demo application.
Steps to reproduce:
- Run app for the first time
- Create a Realtime instance with an app key
- Call `push.activate` (start a token request **A** for the device registration) and right after start the Realtime connection (start a token request **B** for web socket connection)
- If the request **B** finishes first, then the `push.activate` will not end because the `authorize` callback isn't reached.
=> Fix consecutive Authorizations

Source/ARTLocalDevice.m, Source/ARTLocalDeviceStorage.m, Source/ARTNSMutableRequest+ARTPush.m, Source/ARTPushActivationEvent.h, Source/ARTPushActivationEvent.m, Source/ARTPushActivationState.m, Source/ARTPushActivationStateMachine.m, Spec/PushActivationStateMachine.swift, Spec/PushAdmin.swift, Spec/PushChannel.swift
- `deviceUpdateRegistration` method was setting a wrong Authorization header and was trying to read an updated `deviceIdentityToken` from the response body. Since that field doesn't exist, the local `deviceIdentityTokenDetails` was updated with a `token=nil`.
=> Push Device Update Registration: fix request authentication

Source/ARTPushActivationStateMachine.m, Spec/PushActivationStateMachine.swift
because it requires 'push-admin' permission and it will fail for 'push-subscribe' only key (Error: 401 "action not permitted").
=> Delete device registration should not use the general-purpose endpoint

Source/ARTPush.m, Spec/MockDeviceStorage.swift, Spec/Push.swift, Spec/PushActivationStateMachine.swift, Spec/TestUtilities.swift
=> Replace NSData.description to stringify device tokens correctly

README.md
Add a note in the release process to test the lib integration in Xcode projects.
=> README: update the release process

Source/ARTChannels.h, Source/ARTChannels.m, Source/ARTRealtimeChannels+Private.h, Source/ARTRealtimeChannels.h, Source/ARTRealtimeChannels.m, Source/ARTRestChannels+Private.h, Source/ARTRestChannels.h, Source/ARTRestChannels.m
We were getting the iterator in the internal queue, but then doing the
copy into public wrappers in the caller's queue. So the internal queue
could then concurrently run a task that mutates the collection while
it's being copied.
Now the copying is done while still on the internal queue, on the common
ARTChannels; Rest and Realtime just provide mappers to copy into the
right public channel type.
Fixes #918 (probably?).
=> Copy channels for public iterate() on internal queue.

Source/ARTRealtime.m, Source/ARTRealtimeChannel.m, Spec/RealtimeClientChannel.swift
The move to FAILED triggers the detached event emitter, which in turn
can cause .release() to remove the channel from the collection. If this
is done while channels are being iterated, that's iterator invalidation
which can cause a crash.
Fixes #918.
=> Move channels to FAILED only after their iterator is done. 

Source/ARTRealtime.m, Spec/RealtimeClientChannel.swift
Turns out #920 wasn't enough, and we need to do that for suspend too.
Now we just copy the whole collection of channels and then operate on
the copy, so we don't have to worry about this in any circumstance.
Fixes #918.
=> Prevent mutate-channels-while-iterating for suspend too.

Spec/Auth.swift
They may change (as this one has). That's what codes are for.
=> Don't assert on error messages.

Source/ARTChannel.m
=> Extract duplicate code from ARTChannel.publish methods

Spec/TestUtilities.swift
We were only setting it when testApplication was nil, ie. on the first
test or if forceNewApp was also true. But that option has nothing to
do with the testApplication, it applies to the ClientOptions instance
produced, whether it's for a fresh Ably application or not.
This allows you to see verbose logs for any given test, not just the
first one.
=> Set logLevel=verbose every time setupOptions is called with debug=true

Source/ARTRealtimeChannel.m
This was somehow left behind as part of the whole #620 effort.
Fixes #926.
=> Make ARTRealtimeChannel.publish thread-safe

Spec/TestUtilities.swift
Test suite was crashing because the file `ably-common/test-resources/crypto-data-256-variable-lengths.json` file doesn't exist.
=> Remove 'crypto-data-256-variable-lengths' reference

Source/ARTFallback+Private.h, Source/ARTFallback.m, Spec/RealtimeClientConnection.swift, Spec/RestClient.swift
The previous way made test mocks pretty incomprehensible.
Just shuffle the given array. In tests, arrange in predefined order.
=> Simplify random fallback host selection.

Spec/RealtimeClientConnection.swift
Now it receives 20% of the messages it used to receive and gets more time to do so.
Fixes #934, for now.
=> Alleviate RTN5 flakiness

Source/ARTHttp.h, Source/ARTHttp.m, Source/ARTWebSocketTransport+Private.h, Source/ARTWebSocketTransport.m
Fixes #964 
This was broken by a recent change that utilised `class` as an argument name for a new method, breaking compilation in a C++ context as `class` is a reserved keyword in that language.
=> Allow library to be used from Objective-C++ (.mm) files again

Source/ARTPush.m, Source/ARTPushActivationStateMachine+Private.h, Source/ARTPushActivationStateMachine.m, Spec/PushActivationStateMachine.swift
While once #966 is fixed new apps won't get into that "illegal"
persisted state, we still need to recover from it for old apps.
This also serves as a workaround, so that the "proper" fix for #966 is
not urgent.
=> If waiting for push device details and got them persisted, re-emit them.

README.md, Source/ARTPush+Private.h, Source/ARTPush.m, Source/ARTRest.m, Spec/Push.swift
Instead, just cache it in the Rest instance.
Otherwise, if the user stops using the first instance and activates push
through a new instance, push activation will still use the first
instance an things won't work as expected.
Unfortunately, this now means that it's possible to have more than one
state machines per process, which is bad; RSH3 mandates that the state
machine must be a single app-wide concurrent process.
Once #966 is fixed, this drawback may be lifted. For now, is has been
documented in the README.
=> Don't have push state machine singleton

Source/ARTPresenceMap.h, Spec/RealtimeClientPresence.swift
Now we have a single hook, directly on the presence map add method, so
that we can't possibly miss an ABSENT message.
Also, attach has been moved to after the hook and event subscription are
set, so that we can't miss those events.
May fix #938.
=> Simplify hooks on RTP2f test

Ably.xcodeproj/project.pbxproj, Source/ARTChannel+Private.h, Source/ARTChannel.h, Source/ARTChannel.m, Source/ARTChannelOptions.h, Source/ARTChannels.m, Source/ARTJsonLikeEncoder.m, Source/ARTProtocolMessage.h, Source/ARTProtocolMessage.m, Source/ARTRealtimeChannel+Private.h, Source/ARTRealtimeChannel.h, Source/ARTRealtimeChannel.m, Source/ARTRealtimeChannelOptions.h, Source/ARTRealtimeChannelOptions.m, Source/ARTRealtimeChannels+Private.h, Source/ARTRealtimeChannels.h, Source/ARTRealtimeChannels.m, Source/ARTRestChannel.h, Source/ARTRestChannel.m, Source/Ably.h, Spec/RealtimeClientChannel.swift, Spec/RealtimeClientChannels.swift, Spec/RestClientChannels.swift
- (RSL7) Channel#setOptions takes a ChannelOptions object and sets or updates the stored channel options, then indicates success
- (RTL16) Channel#setOptions takes a ChannelOptions object and sets or updates the stored channel options.
- (RTL16a) If the user has provided either ChannelOptions.params or ChannelOptions.modes and the channel is in either the attached or attaching state, Channel#setOptions sends an ATTACH message to the server with the params & modes encoded per RTL4, and indicates success once the server has replied with an ATTACHED (or indicates failure if the channel becomes detached or failed before that happens, as with Channel#attach); else it indicates success immediately
=> Channel options (per 1.2 spec)

Ably.podspec, Cartfile
Bringing in our KSCrash fork modification (https://github.com/ably-forks/KSCrash/pull/3) to prefix all category names, as well as header file names, to prevent build clashes when combined with other libraries.
=> Update KSCrash dependency

Spec/TestUtilities.swift
For some reason, test app creation started hanging forever in my
machine. Using the extras dispatch queue to perform it fixed it. I guess
it's good we don't use the main queue unless required anyway.
=> Use tests dispatch queue, not main, to POST /apps.

Source/ARTAuth.m, Source/ARTRealtime.m, Spec/Auth.swift, Spec/RealtimeClientConnection.swift
Removed complex and apparently unnecessary logic on error protocol message handler. No tests broken by this.
I first thought this was an issue with RSA4b, so I also added a missing test for it and some documentation.
Fixes #984.
=> Fix handling of token error when first connecting.

Source/ARTJsonLikeEncoder.m, Source/ARTNSMutableRequest+ARTPush.m, Source/ARTPushChannelSubscriptions.m, Source/ARTPushDeviceRegistrations.m, Source/ARTRest.m, Source/ARTTypes.h, Source/ARTTypes.m
On my current project that uses Ably, I see some name collisions with other Objective-C code that defines a `Utilities` extension on `NSString` and `NSDate`. This PR renames those extensions to `ARTUtilities` and adds an `art_` prefix to these methods to avoid further Objective-C namespace collisions. I’ve used `NS_SWIFT_NAME` to ensure that the names don’t change for Swift code.
=> Fix Objective-C namespace collisions

Source/ARTAuth.m, Source/ARTRealtime.m, Source/ARTTypes.h, Source/ARTTypes.m
This is a corner case, but users may encounter it.
=> Avoid leak from user incorrectly holding to authCallback's callback.

Spec/Auth.swift, Spec/RealtimeClientChannel.swift, Spec/RealtimeClientConnection.swift
- For example, if you run a solo test where you don't need internet connection, then the test will fail because there are AblyTest.commonAppSetup() calls inside of 'context' scopes which are executed even if you select only one test to run.
=> Should not wait for AblyTest.options in 'context' scope

Source/ARTRealtime+Private.h, Source/ARTRest+Private.h, Source/ARTRest.m
Fixes #1030.
I've not been able to reproduce the thread sanitizer data race that the customer has experienced at runtime, so I have taken the approach of inspecting this area of the codebase and improving what I see while trying to keep the scope of change as minimal as possible.
The diff's a bit messier than I would have liked as I've also fixed some indentation and thrown in some `const`s. There's a little bit more detail in my commit messages, in particular https://github.com/ably/ably-cocoa/commit/471cce18a4b4bee35184f4ae0e498d9f5c1ec6cc.
Meanwhile I would like to invite @SlaunchaMan to try directly from this branch to see if it solves the issue, assuming it is regularly reproducible! Jeff, could you please rebuild using this Cocoapods directive instead of the one you currently have …
=> Improve unhandled exception handling code

README.md
This change fixes a typo in the README file, which contained incorrect instructions for CocoaPods.
=> Correct CocoaPods instruction

README.md
Frameworks are natively supported by Swift, and are recommended approach to use external modules. Therefore it makes sense to recommend specifying use of frameworks in the CocoaPods instructions for Swift users, which is what this PR adds.
=> Add `use_frameworks!` recommendation

Source/ARTAuth.m, Source/ARTPush+Private.h, Source/ARTPush.m, Source/ARTRealtime+Private.h, Source/ARTRest+Private.h, Spec/Push.swift
=> Fix Push State Machine delegate syncing the main queue

Source/ARTHttp.m, Source/ARTRestChannel.m, Spec/Auth.swift, Spec/RestClientChannel.swift
=> Fixes 40012 "Malformed message; invalid clientId" when message has no clientId and credentials can assume any clientId

Ably-SoakTest-AppUITests/SoakTestWebSocket.swift, Ably.podspec, Cartfile, Cartfile.resolved, Source/ARTWebSocket.h, Source/ARTWebSocketTransport+Private.h, Source/ARTWebSocketTransport.m, Spec/TestUtilities.swift
This updates the SocketRocket dependency to 0.5.2-ably-8.
When I run `make test_iOS` with Xcode 12, I get a few test failures:
```
Ably-iOS-Tests:
Auth.authorize__two_consecutive_authorizations__using_Realtime_and_connection_is_CONNECTING__should_call_each_Realtime_authorize_callback()
RealtimeClientConnection.Connection__connection_failures_once_CONNECTED__DISCONNECTED_message_contains_a_token_error__and_the_library_does_not_have_a_means_to_renew_the_token_
_the_connection_will_transition_to_the_FAILED_state()
RealtimeClientPresence.Presence__should_receive_all_250_members()
```
Is this to be expected? I'm a little unsure about what I need to do to validate that my changes haven't broken anything (although, I'd be surprised if they'd introduced any issues other than compilation errors…)
=> Update SocketRocket dependency to 0.5.2-ably-8

Source/ARTAuth.m, Spec/Push.swift
Related with https://ably-real-time.slack.com/archives/CSQEKCE81/p1615834853011400 cc @cruickshankpg
=> Fix of RSH3a2a1 implementation when the clientId doesn't change

Source/ARTRealtime.m
Calling `[ARTRealtime transitionSideEffects:]` while in a failed connection state returns a nil reference to `ARTEventListener*`. 
This PR adds a nil-pointer check to avoid a crash, which fixes #1083.
=> Fixed crash by adding a nil-pointer check.

.gitignore, Spec/RealtimeClient.swift, Spec/RealtimeClientChannel.swift, Spec/RealtimeClientConnection.swift, Spec/RealtimeClientPresence.swift
These failing tests have been blocking PRs landing into `ably-cocoa`, including changes that only touch the `README.md` file. I've set a reminder to re-enable tests on Friday, and if there is a fix earlier, I will disable them sooner.
Every section that was commented out has been commented with
```swift
// FIXME Fix flaky presence tests and re-enable. See https://ably-real-time.slack.com/archives/C030C5YLY/p1623172436085700
```
I did try to find an option to "ignore" or temporarily disable them in the  [Nimble docs](https://github.com/Quick/Nimble), but I didn't find anything.
=> Temporarily disable tests to pass flaky presence tests

Source/ARTDeviceDetails.h, Source/ARTJsonLikeEncoder.m, Source/ARTLocalDevice.h, Spec/PushAdmin.swift
The deviceSecret should be in `ARTLocalDevice`, instead of `ARTDeviceDetails`. ARTLocalDevice inherits from ARTDeviceDetails, so not much is changing.
The feature spec was previously inconsistent, and there is a PR to fix this: https://github.com/ably/docs/pull/1141
=> Move deviceSecret into ARTLocalDevice

README.md
A small change to the readme (2 actual lines of content) because Carthage is required to be installed. I propose we use bullet points going forward to avoid the diff being larger than necessary.
One of the reasons for this PR is to test the CI (checks tab), it was failing.
=> Readme improvement: Add install carthage step, and remove `make setup`

SocketRocket/SocketRocket/Internal/Proxy/ARTSRProxyConnect.m
This finally fixes SocketRocket portion of NSURLSession API insecure usage, which was originally fixed here https://github.com/ably-forks/SocketRocket/issues/7, but then messed up with https://github.com/ably/ably-cocoa/pull/1090
=> Fix for potentially insecure usage of the NSURLSession API

Source/ARTRealtime.m, Source/ARTRealtimeChannel+Private.h, Source/ARTRealtimeChannel.m
=> Reattaching channels in compliance with RTN15c3

Ably.xcodeproj/project.pbxproj, Source/ARTDeviceIdentityTokenDetails.m, Source/ARTPushActivationEvent.m, Source/ARTPushActivationState.m, Source/ARTPushActivationStateMachine.m, Source/ARTTypes.h, Source/ARTTypes.m, Spec/ARTArchiveTests.m
`NSKeyedUnarchiver` becomes more tricky with new version of iOS SDK. So it took a little while to figure out how to use it properly. With iOS 11 it is not happy if you indirectly allow to parse any type within an archive, so now it requires to provide allowed classes list. So I did.
Also I've provided dedicated test for unarchiving function specifically in Objective-C so Swift wouldn't interfere with its under the hood collection types conversions.
=> Fix/1188 Added allowed class for NSKeyedUnarchiver

Examples/SPM/Package.resolved, Examples/SPM/Package.swift
Our example app currently uses an environment variable to find the SDK (Ably Cocoa). It's simpler to use a relative path, resulting in smaller `Package.swift` and `Package.resolved` files.
You may notice that this example app uses AblyDeltaCodec v1.3.2. Even though Ably Cocoa has not been released to use AblyDeltaCodec, `1.3.2` this example app uses it because Ably Cocoa only specifies a **minimum** version of AblyDeltaCodec.
=> Example app: Use relative path of Ably Cocoa

Source/ARTCrypto.m
=> Replaced deprecated kCCAlgorithmAES128 with kCCAlgorithmAES

Spec/PushActivationStateMachine.swift
Renames a function that defines some reusable tests.
Same motivation as #1225, except here the reusable function already exists – we just need to name it correctly.
=> [Groundwork for #1201] Prefix `rsh3*` function names with `reusableTests`

Spec/PushActivationStateMachine.swift
Replaces a call to `pending` in our tests (the only one in the codebase) with a call to `xit`.
It’s groundwork for removing the Quick testing framework using an automated migrator tool (#1201). The migrator won’t know what to do with a call to `pending` (see commit message for more details).
=> [Groundwork for #1201] Replace call to `pending` with `xit`

Spec/Auth.swift, Spec/RealtimeClientChannel.swift, Spec/RealtimeClientConnection.swift, Spec/RealtimeClientPresence.swift, Spec/RestClient.swift, Spec/RestClientChannel.swift, Spec/TestUtilities.swift
Unrolls some test-defining loops into individual calls to a reusable function. See first commit message for more details. Similar to #1225.
It’s groundwork for removing the Quick testing framework using an automated migrator tool (#1201). Same motivation as #1225 (but the solution is simpler here as it doesn’t need us to create a `reusableTests` function).
=> [Groundwork for #1201] Unroll simple test-defining loops in test files

Spec/Auth.swift, Spec/Crypto.swift, Spec/PushActivationStateMachine.swift, Spec/RealtimeClientPresence.swift, Spec/Stats.swift, Spec/TestUtilities.swift
Unrolls some test-defining loops into individual calls to a reusable function. See first commit message for more details.
It’s groundwork for removing the Quick testing framework using an automated migrator tool (#1201). The
migrator that I’m writing won’t be able to handle arbitrary statements like `forEach` calls or loops, so we need to replace them with something it knows how to handle, namely a call to a function named with a special `reusableTests` prefix.
=> [Groundwork for #1201] Unroll test-defining loops in test files into `reusableTests` function calls

.github/workflows/check-pod.yml, Scripts/carthage-with-workaround-for-issue-3019.sh
This fixes the `carthage-with-workaround-for-issue-3019.sh` script to work for Xcode 13 as well as Xcode 12. I noticed this because GitHub seem to have upgraded our macOS version, causing the default Xcode version to increase (see commit message).
Whilst I was investigating, I also split the `check-pod` workflow into multiple steps, to make it easier to see which stage of the job failed.
=> Fix Carthage #3019 workaround for Xcode 13

Spec/PushAdmin.swift
Removes a capture in some trailing closures in the tests. See commit message for more details.
Whilst I was there, I also changed some `var`s to `let`s.
It’s groundwork for removing the Quick testing framework using an automated migrator tool (#1201). The
migrator that I’m writing won’t be able to handle the capture lists in the QuickSpec method call trailing closures, so I’m replacing them.
=> [Groundwork for #1201] Remove capture in Quick method call trailing closures

Spec/Auth.swift, Spec/Crypto.swift, Spec/ObjectLifetimes.swift, Spec/RealtimeClient.swift, Spec/RealtimeClientPresence.swift, Spec/RestClientStats.swift
Removes some arbitrary statements from `spec` / `describe` / `context` level, moving them into related variable declarations.
It’s groundwork for removing the Quick testing framework using an automated migrator tool (#1201). The migrator that I’m writing won’t be able to handle these statements, so I'm moving them inside statements that it knows how to handle. See the first commit message for more details.
=> [Groundwork for #1201] Remove floating statements at `spec` / `describe` / `context` level

Spec/RestClient.swift
Moves the setting of `ARTDefault.fallbackRetryTimeout` from the top level of `context` to inside `beforeEach` blocks. See commit message for explanation of why I think it was an error to put this code at `context` level.
In theory, yes, although I think in practice it doesn’t since the existing code was accidentally working (see commit message).
Original motivation that caused me to notice this was #1232 (removing arbitrary statements at `context` level).
=> [Groundwork for #1201, but also a fix] Fix setting of fallback retry timeout in tests

Spec/Auth.swift, Spec/RealtimeClientChannel.swift, Spec/RealtimeClientConnection.swift, Spec/RestClientChannel.swift, Spec/Stats.swift
Removes or renames some variables at the `spec` / `describe` / `context` level.
No, it's just a refactor (moving variable declarations inside other ones, or renaming variables).
It’s groundwork for removing the Quick testing framework using an automated migrator tool (#1201). The migrator that I’m writing will pull all `spec` / `describe` / `context` level variable and function declarations in a file into a flattened file-wide list of global declarations. This might lead to clashes if multiple contexts use the same variable name. So we rename / remove things to avoid these clashes.
I had hoped to avoid this step, by making the migrator automatically rename variables to avoid clashes. I had a solution _almost_ working with [`swift-refactor`](https://github.com/apple/swift/tree/main/tools/sw …
=> [Groundwork for #1201] Rename or remove clashing variables

Spec/Auth.swift, Spec/RealtimeClientConnection.swift
Rewrites test descriptions so that they don't contain any symbols which, if removed, would change the meaning of the test description.
It’s groundwork for removing the Quick testing framework using an automated migrator tool (#1201).  The migrator that I’m writing will convert all symbols in test descriptions to underscores in the emitted method names. This is okay most of the time, but we have a few places where the symbols have meaning, and removing them will change the description of the test. The migrator emits a warning when it thinks this is the case, but it’s up to us to look at this output and decide which ones need changing.
=> [Groundwork for #1201] Rewrite test descriptions containing meaningful symbols

Ably.xcodeproj/project.pbxproj, Cartfile.private, Cartfile.resolved, Spec/Auth.swift, Spec/Crypto.swift, Spec/DeltaCodec.swift, Spec/Info-iOS.plist, Spec/Info-macOS.plist, Spec/Info-tvOS.plist, Spec/ObjectLifetimes.swift, Spec/Push.swift, Spec/PushActivationStateMachine.swift, Spec/PushAdmin.swift, Spec/PushChannel.swift, Spec/ReadmeExamples.swift, Spec/RealtimeClient.swift, Spec/RealtimeClientChannel.swift, Spec/RealtimeClientChannels.swift, Spec/RealtimeClientConnection.swift, Spec/RealtimeClientPresence.swift, Spec/RestClient.swift, Spec/RestClientChannel.swift, Spec/RestClientChannels.swift, Spec/RestClientPresence.swift, Spec/RestClientStats.swift, Spec/RestPaginated.swift, Spec/Stats.swift, Spec/Stringifiable.swift, Spec/TestUtilities.swift, Spec/Utilities.swift
Removes the [Quick testing framework](https://github.com/Quick/Quick).
See #1201 for details. The main two reasons are:
- to get the ability to run individual tests using Xcode’s UI;
- using the Apple native test framework instead of a third-party library that will be unfamiliar to many Swift developers.
I wrote an [automated migrator tool](https://github.com/ably/quick-to-xctest-migrator) to do the bulk of the work here. (The code for the migrator is still rather messy. We're thinking about tidying it up to make it publicly available, but it's not there yet.)
Each of the steps below is a commit which I recommend reviewing individually (else you'll struggle to make _any_ sense of this PR, I think):
1. (Migrator tool) Move all of the `spec` / `describe` / `context` level local variable and …
=> Remove the Quick testing framework

Ably.xcodeproj/project.pbxproj
The `Carthage/Build/iOS` (and similarly for other platforms) directories indeed do not exist. I assume that once upon a time they did. But anyway, I don’t think we need any framework search paths configured, since our Carthage frameworks’ locations are configured via the members of the Frameworks group in the Xcode project.
=> Fix linker warnings about missing directories

Ably.xcodeproj/project.pbxproj, Ably.xcodeproj/xcshareddata/xcschemes/Ably-SoakTest-App.xcscheme, Ably.xcodeproj/xcshareddata/xcschemes/Ably-iOS-Tests.xcscheme, Ably.xcodeproj/xcshareddata/xcschemes/Ably-iOS.xcscheme, Ably.xcodeproj/xcshareddata/xcschemes/Ably-macOS-Tests.xcscheme, Ably.xcodeproj/xcshareddata/xcschemes/Ably-macOS.xcscheme, Ably.xcodeproj/xcshareddata/xcschemes/Ably-tvOS-Tests.xcscheme, Ably.xcodeproj/xcshareddata/xcschemes/Ably-tvOS.xcscheme
This makes the slightly-annoying warning go away. The recommended changes were to increase our deployment target to iOS 12, which I refused.
=> Complete Xcode 13.1’s “Update to recommended settings” wizard

Source/ARTLocalDevice+Private.h, Source/ARTLocalDevice.h, Source/ARTLocalDevice.m, Source/ARTPushActivationState.m, Spec/Tests/PushActivationStateMachineTests.swift
This PR goes instead of #1253, because that one was addressing two different issues (not respecting [RSH3g2a](https://docs.ably.io/client-lib-development-guide/features/#RSH3g2a) and [RSH8b](https://ably.com/documentation/client-lib-development-guide/features#RSH8b)).
This addresses RSH3g2a only (Issue #1177), For RSH8b there is another issue - https://github.com/ably/ably-cocoa/issues/1256
=> Fix/1177 full reset device details (RSH3g2a only)

Source/ARTRealtimeChannel.m, Spec/Test Utilities/NSObject+TestSuite.m, Spec/Tests/RealtimeClientChannelTests.swift
When calling `-[ARTRealtimeChannel setOptions:callback:]`, the passed options are not used to update the options of this instance’s REST channel. This means that, for example, if we update the realtime channel’s cipher options, these options will not be used to decrypt messages subsequently fetched using the `-history:*` methods.
I think this is something we missed when fixing #1207.
This issue is causing ably/ably-flutter#296.
Closes #1265.
=> When setting realtime channel options, pass through to REST channel

Spec/Tests/AuthTests.swift, Spec/Tests/PushActivationStateMachineTests.swift, Spec/Tests/PushAdminTests.swift, Spec/Tests/PushChannelTests.swift, Spec/Tests/RestClientTests.swift
Since the purpose of this PR is to improve readability of the tests, I've only replaced places that were overwhelmed with `guard` statements followed one after another. Also standalone cases where clause were one of a bunch mentioned in previous sentence (in most cases).
=> XCTUnwrap instead of guard

.github/workflows/integration-test-iOS11.yaml, .github/workflows/integration-test-iOS12.yaml, .github/workflows/integration-test-macOS.yaml, .github/workflows/integration-test-tvOS.yaml
Hopefully will speed CI jobs up a bit. We should probably have done this as part of #1274.
=> Don’t build Carthage libraries for unnecessary platforms

.gitignore
It's where Fastlane-triggered builds put their derived data. Handy to have this ignored when running Fastlane locally.
=> Make Git ignore `derived_data` directory

Scripts/local_dev_upload_test_results.sh, Scripts/upload_test_results.sh
I forgot that `GITHUB_BASE_REF` and `GITHUB_HEAD_REF` are only set for builds triggered by pull requests.
=> Fix test observability server upload on `main`

Examples/AblyPush/AblyPushExample/AblyHelper.swift
=> Removed call to `registerForRemoteNotifications` from basic APNS example

Spec/Tests/RealtimeClientPresenceTests.swift
Fixes the tests described in 
- #1309
- #1321 
- #1331
- #1333 
See commit messages for more details.
Here's the evidence I have that makes me suspect they're now fixed.
- [These results](https://test-observability.herokuapp.com/repos/ably/ably-cocoa/uploads?branches%5B%5D=1309-new-speculative-fix-to-test-case-114e01a8-8971-4c3a-9cb7-0bb128e2749e&createdBefore=&createdAfter=&failureMessage=) just contain the fix for #1309.
- 82 uploads, no failures in that test.
- [These results](https://test-observability.herokuapp.com/repos/ably/ably-cocoa/uploads?branches%5B%5D=1309-new-speculative-fix-for-test-case-84c9fbc5-8882-4010-ba99-3e44d1793397&createdBefore=&createdAfter=&failureMessage=) just contain the fix for #1321.
-  74 test runs, no failures in that test.
- [These …
=> (#1309, #1321, #1331, #1333) Fixes for 4 presence tests

Source/ARTRest.m
This slipped past me and code review. I knew that `clientId_nosync` needed to be called on the same thread as its containing method (I even mentioned it in code review) and yet I didn’t actually do it 🤦.
=> Fix mistake in my recent PR #1332

Spec/Tests/PushActivationStateMachineTests.swift
The functionality it tests was removed in cc03343.
=> Remove outdated skipped test

Spec/Tests/RestClientPresenceTests.swift
This was missed in baf5a30 (since the test is skipped).
=> Fix channel name in RestClientPresenceTests.skipped__test__002

Scripts/upload_test_results.sh
So that if an error occurs in the upload we can see what it was.
=> Print observability server response body

Spec/Tests/RealtimeClientConnectionTests.swift
=> Added XCTestExpectation to wait for all attemted fallback hosts (test-092)

Spec/Tests/RealtimeClientConnectionTests.swift
Most failures for this test are related to the test timeout. One of the causes is disconnect message failed to be received in time. To eliminate this and simulate sudden `.disconnected` event I've added manual disconnection. This change will not help in case of timeout for `connected` event.
=> Premature disconnect to test reconnect within 10 seconds

Docs/tools-for-investigating-test-failures.md
This script already exists on branch `1279-run-tests-in-loop`; I'm just adding some documentation.
=> Add documentation about script for modifying GitHub workflows

Ably.xcodeproj/project.pbxproj
For some reason they were only running on tvOS, which seems like an accident.
=> Add GCDTests and StringifiableTests to all platforms’ test suites

Source/ARTBaseMessage.h, Source/ARTDeviceDetails.h, Source/ARTDeviceDetails.m, Source/ARTDevicePushDetails.h, Source/ARTLocalDevice.h, Source/ARTPresenceMap.h, Source/ARTProtocolMessage.h, Spec/Tests/PushAdminTests.swift
=> Added missing `strong` property attributes

CONTRIBUTING.md
Symlink command arguments seems to be reversed.
According to [this website](https://www.howtogeek.com/297721/how-to-create-and-use-symbolic-links-aka-symlinks-on-a-mac/) 
The command should be 
`ln -s /path/to/original /path/to/link
`
=> Fix symlink command on contributing guide

Spec/Tests/RestClientChannelTests.swift
It should be within a `push` object.
Closes #1448
=> A `notification` isn't a valid extras field

Source/Private/ARTOSReachability.m
Closes #1380 and probably #593
=> Fix of the crash in the `ARTOSReachability`

Spec/Tests/RealtimeClientConnectionTests.swift
Fixes an intermittent failure. See commit messages for more details.
=> (#1406) Fix and re-enable `RealtimeClientConnectionTests.test__081`

Spec/Tests/UtilitiesTests.swift
This fixes the failure “Waited more than 0.3 seconds” in the waitUntil, which I reproduced by running the test once locally.
The waitUntil timeout needs to be higher than the asyncAfter wait, at least by a few milliseconds. So let’s just use the normal test timeout value.
Relates to #1406.
=> (#1406) Fix and re-enable `UtilitiesTests.test__012`

.github/workflows/check-pod.yaml, CONTRIBUTING.md
This fixes the failures we’ve been seeing in that job recently. See commit messages for more details.
=> Lock to using Xcode 13.4.1 in `check-pod` CI job

.github/workflows/check-pod.yaml
Commit 938fe91 contained two different issues:
1. There was a typo `carthage-build-framework` instead of `carthage-built-framework`;
2. We actually required _two_ levels of directories to provide the desired effect of the GitHub artifact not containing a zip file at the top level.
This fixes those issues.
=> Fix CI step that prepares built framework artifact

Source/ARTClientOptions+Private.h, Source/ARTClientOptions.h, Source/ARTClientOptions.m, Source/ARTRest.m, Source/ARTWebSocketTransport.m, Spec/Tests/ClientOptionsTests.swift, Spec/Tests/RestClientTests.swift
This removes the non-spec `-[ARTClientOptions addAgent:version:]` and replaces it with a dictionary `-agents` property, hence implementing [RSC7d6](https://sdk.ably.com/builds/ably/specification/main/features/#RSC7d6) as described by the spec.
Closes #1525.
=> Bring `ARTClientOptions#agents` in line with spec

Source/ARTLocalDeviceStorage.m, Source/ARTRest+Private.h, Source/ARTRest.m
Closes #1521 
We don't use `ARTLocalDeviceStorage` on macos, hence `SecKeychainItemDelete` can be safely removed.
The code itself was copied from `SAMKeychain` library. More info: https://github.com/soffes/SAMKeychain/blob/d3d64f8c5fa14bf2adb2d51a18ee8b6639232ca5/Sources/SAMKeychainQuery.m#L83
=> Removed deprecated `SecKeychainItemDelete`

Spec/Test Utilities/TestUtilities.swift
Closes https://github.com/ably/ably-cocoa/issues/1522
With the new version of the compiler it's not allowed anymore to use `open` modifier because non-'@objc' property in extensions cannot be overridden, hense requirment to use `public`.  But `_allHeaderFields` is't used anywhere and looks like it was added for the sake of provided comment to it. So I've removed it.
=> Removed `HTTPURLResponse._allHeaderFields`

SocketRocket/SocketRocket/Internal/Proxy/ARTSRProxyConnect.m, SocketRocket/SocketRocket/Internal/RunLoop/ARTSRRunLoopThread.h, SocketRocket/SocketRocket/Internal/RunLoop/ARTSRRunLoopThread.m, SocketRocket/SocketRocket/NSRunLoop+ARTSRWebSocket.h, SocketRocket/SocketRocket/NSRunLoop+ARTSRWebSocket.m
Closes #1516 
<strike>Upgraded SocketRocket thread to `NSQualityOfServiceUserInteractive`</strike> to avoid runtime warning "Thread running at QOS_CLASS_USER_INTERACTIVE waiting on a lower QoS thread running at QOS_CLASS_DEFAULT. Investigate ways to avoid priority inversions"
=> Fix of priority inversion

Source/ARTRealtimeTransport.h, Source/ARTWebSocketTransport.h, Source/ARTWebSocketTransport.m
This was introduced in eb3a8f6, where as far as I can tell it did nothing useful, since the logger (which is using `ARTLog`’s default behaviour) only logs messages of level `warn` or above, and we only ever log to it at level `info`, hence it never logs anything.
I’m not sure what the original intention was behind this logger, but it seems safe to remove it.
Closes #1556.
=> Remove `protocolMessagesLogger` from `ARTWebSocketTransport`

Ably.xcodeproj/project.pbxproj, Source/ARTErrorChecker.m, Source/ARTRealtime.m, Source/ARTRest.m, Source/ARTResumeRequestResponse.m, Source/Ably.modulemap, Source/PrivateHeaders/Ably/ARTErrorChecker.h, Source/PrivateHeaders/Ably/ARTResumeRequestResponse.h, Source/include/Ably.modulemap, Test/Test Utilities/MockErrorChecker.swift, Test/Tests/DefaultErrorCheckerTests.swift, Test/Tests/ResumeRequestResponseTests.swift
This introduces a `ARTResumeRequestResponse` type to represent the Realtime service’s response to a connection resume request. I’d like us to try incorporating it into https://github.com/ably/ably-cocoa/pull/1496.
See commit messages for more details.
=> Add a type to represent the Realtime service’s response to a connection resume request

Source/ARTRealtime.m
=> Call to `connect` instead of `_connect` to avoid potential race conditions

Source/ARTRealtimeChannel.m, Source/ARTRealtimeChannels.m, Source/PrivateHeaders/Ably/ARTRealtimeChannel+Private.h
It buys us nothing over just using the initializer and it’s just another thing to have to update when we change the initializer’s signature.
=> Remove `ARTRealtimeChannelInternal` factory method

Ably.xcodeproj/project.pbxproj, Source/ARTJitterCoefficientGenerator.m, Source/Ably.modulemap, Source/PrivateHeaders/Ably/ARTJitterCoefficientGenerator.h, Source/include/Ably.modulemap, Test/Test Utilities/MockJitterCoefficientGenerator.swift, Test/Test Utilities/StaticJitterCoefficients.swift, Test/Tests/DefaultJitterCoefficientGeneratorTests.swift
We’ll use this in the implementation of #1431.
=> Add protocol for generating `RTB1b`’s jitter coefficient

Test/Info-macOS.plist, Test/Info-tvOS.plist
My mistake in 5d20fbf. Unfortunately it didn’t generate any loud runtime error; I only just now noticed a warning in the logs when running the tests on macOS locally.
I’m not sure what the consequences of this omission have been; it means that the line `AsyncDefaults.timeout = testTimeout` hasn’t been executing on macOS and tvOS. I wonder if that might have had some effect on test stability?
=> Fix qualified name of `AblyTestsConfiguration` for macOS and tvOS

Ably.xcodeproj/project.pbxproj, Source/ARTBackoffRetryDelayCalculator.m, Source/ARTConstantRetryDelayCalculator.m, Source/Ably.modulemap, Source/PrivateHeaders/Ably/ARTBackoffRetryDelayCalculator.h, Source/PrivateHeaders/Ably/ARTConstantRetryDelayCalculator.h, Source/PrivateHeaders/Ably/ARTRetryDelayCalculator.h, Source/include/Ably.modulemap, Test/Test Utilities/BackoffCoefficients.swift, Test/Test Utilities/TestUtilities.swift, Test/Tests/BackoffRetryDelayCalculatorTests.swift, Test/Tests/ConstantRetryDelayCalculatorTests.swift
This provides a calculator which determines the amount of time to wait before retrying an operation. We’ll use it in the implementation of #1431.
See commit messages for more details.
=> Add retry delay calculator

Ably.xcodeproj/project.pbxproj, Source/ARTClientOptions.m, Source/ARTRealtimeChannels.m, Source/ARTRestChannels.m, Source/Ably.modulemap, Source/PrivateHeaders/Ably/ARTClientOptions+Private.h, Source/PrivateHeaders/Ably/ARTClientOptions+TestConfiguration.h, Source/include/Ably.modulemap
I’m going to add further dependencies to this in the implementation of #1431.
=> Move testing configuration to separate `ARTClientOptions` header

Ably.xcodeproj/project.pbxproj
Closes [1559](https://github.com/ably/ably-cocoa/issues/1559)
`Embed` setting leads to dependency frameworks copied twice into AppStore archive which is not allowed.
=> Do not embed dependency frameworks

Source/ARTCrypto.m, Source/PrivateHeaders/Ably/ARTCrypto+Private.h
This removes some logging functionality which the crypto classes are unable to make use of. See commit messages for more details.
=> Remove some unusable logging in crypto classes

Ably.xcodeproj/project.pbxproj, Source/ARTAttachRequestMetadata.m, Source/ARTChannelStateChangeMetadata.m, Source/ARTConnectionStateChangeMetadata.m, Source/ARTRealtime.m, Source/ARTRealtimeChannel.m, Source/ARTStatus.m, Source/Ably.modulemap, Source/PrivateHeaders/Ably/ARTAttachRequestMetadata.h, Source/PrivateHeaders/Ably/ARTChannelStateChangeMetadata.h, Source/PrivateHeaders/Ably/ARTConnectionStateChangeMetadata.h, Source/PrivateHeaders/Ably/ARTRealtime+Private.h, Source/PrivateHeaders/Ably/ARTRealtimeChannel+Private.h, Source/include/Ably.modulemap, Source/include/Ably/ARTStatus.h, Test/Tests/RealtimeClientChannelTests.swift, Test/Tests/RealtimeClientPresenceTests.swift
This creates objects that encapsulate all of the metadata related to a request to perform an operation that may cause a connection or channel to emit a state change. See commit messages for more details.
This is a refactor, which will form part of our implementation of #1431.
=> Refactor transitions

Source/ARTRealtimeChannel.m
I forgot to do this in 47e3a59.
=> Pass `retryAttempt` from attach metadata to state change metadata

Test/Test Utilities/TestUtilities.swift, Test/Tests/RealtimeClientChannelTests.swift, Test/Tests/RealtimeClientConnectionTests.swift
Some low-hanging fruit that I noticed whilst looking into #1604 (removing global mutable state in test suite).
=> Remove some unnecessary use of `static var` in test suite

Ably.xcodeproj/project.pbxproj, Source/ARTInternalLog.m, Source/ARTLogAdapter.m, Source/Ably.modulemap, Source/PrivateHeaders/Ably/ARTInternalLog.h, Source/PrivateHeaders/Ably/ARTLogAdapter.h, Source/PrivateHeaders/Ably/ARTVersion2Log.h, Source/include/Ably.modulemap, Test/Test Utilities/MockVersion2Log.swift, Test/Tests/ARTInternalLogTests.m, Test/Tests/InternalLogTests.swift, Test/Tests/LogAdapterTests.swift
This introduces the types that will form the basis of our work for the upcoming [Logging Milestone](https://github.com/ably/ably-cocoa/milestone/6). See commit messages for more details.
Resolves #1619, resolves #1620, resolves #1621.
=> Introduce new logging types

CHANGELOG.md, Source/ARTInternalLog.m, Source/ARTLogAdapter.m, Source/ARTRealtimeChannel.m, Source/PrivateHeaders/Ably/ARTInternalLog.h, Source/PrivateHeaders/Ably/ARTLogAdapter.h, Source/PrivateHeaders/Ably/ARTVersion2Log.h, Source/include/Ably/ARTLog.h, Test/Test Utilities/MockVersion2Log.swift, Test/Tests/InternalLogTests.swift, Test/Tests/LogAdapterTests.swift
It’s only being used in one place internally. Furthermore, I don’t think it makes sense to log an error message without describing the context in which the error occurred. We’ll revisit whether there’s something more appropriate this should be replaced by, as part of #1617 and #1628.
=> Stop using the `-logWithError:` method

Source/PrivateHeaders/Ably/ARTJsonLikeEncoder.h, Source/PrivateHeaders/Ably/ARTPushChannel+Private.h, Source/PrivateHeaders/Ably/ARTPushChannelSubscriptions+Private.h, Source/PrivateHeaders/Ably/ARTPushDeviceRegistrations+Private.h, Source/PrivateHeaders/Ably/ARTQueuedDealloc.h, Source/PrivateHeaders/Ably/ARTURLSession.h, Source/PrivateHeaders/Ably/ARTWebSocket.h
These aren’t necessary when using `#import`, and we don’t use them for most of the headers in the project. These probably just came from using Xcode’s default header file template.
=> Remove unnecessary `#include` guards

Source/ARTTime.m, Source/ARTTokenParams.m, Source/PrivateHeaders/Ably/ARTEventEmitter+Private.h, Source/PrivateHeaders/Ably/ARTFallback+Private.h, Test/AblyTests-Bridging-Header.h
I can’t think of any reason why these should be `#include` (`#import` is normally always used in Objective-C code), so let’s be consistent with the rest of the codebase.
=> Replace usage of `#include` with `#import`

Test/Test Utilities/TestUtilities.swift
And add a private queue to the one place where it’s actually used, instead.
=> Remove shared `TestUtilities.extraQueue`

Test/Test Utilities/TestUtilities.swift
Part of #1604 (removing shared mutable state in test suite). A UUID is just as good, and one less variable to worry about.
=> Remove static `setupOptionsCounter` variable

Source/ARTHttp.m, Source/ARTRest.m, Source/PrivateHeaders/Ably/ARTHttp.h, Test/Test Utilities/TestUtilities.swift, Test/Tests/AuthTests.swift, Test/Tests/PushAdminTests.swift, Test/Tests/RealtimeClientChannelTests.swift, Test/Tests/RealtimeClientConnectionTests.swift, Test/Tests/RestClientChannelTests.swift, Test/Tests/RestClientTests.swift, Test/Tests/UtilitiesTests.swift
Adds a couple of missing parameter labels that led to confusing expressions at call sites.
=> Add a couple of missing parameter labels

Test/Test Utilities/TestUtilities.swift
Part of the larger goal of removing `AblyTests.queue` as part of #1604. See commit messages for more details.
=> Remove `TestProxyTransport.queue`

Test/Tests/AuthTests.swift
Part of #1604. See commit messages for more details.
=> Remove top-level mutable state in `AuthTests`

Source/ARTFallback.m, Source/ARTRealtime.m, Source/ARTRest.m, Source/ARTTestClientOptions.m, Source/PrivateHeaders/Ably/ARTFallback+Private.h, Source/PrivateHeaders/Ably/ARTTestClientOptions.h, Source/include/Ably/ARTFallback.h, Test/Tests/RealtimeClientConnectionTests.swift, Test/Tests/RestClientTests.swift
This is part of #1601 (don’t use global SDK state for controlling test behaviour).
=> Make `ARTFallback_shuffleArray` constant

Ably.xcodeproj/project.pbxproj, Source/ARTRealtime.m, Source/ARTRealtimeTransportFactory.m, Source/ARTTestClientOptions.m, Source/Ably.modulemap, Source/PrivateHeaders/Ably/ARTRealtime+Private.h, Source/PrivateHeaders/Ably/ARTRealtimeTransport.h, Source/PrivateHeaders/Ably/ARTRealtimeTransportFactory.h, Source/PrivateHeaders/Ably/ARTTestClientOptions.h, Source/PrivateHeaders/Ably/ARTWebSocketTransport.h, Source/include/Ably.modulemap, Test/Test Utilities/TestProxyTransportFactory.swift, Test/Test Utilities/TestUtilities.swift, Test/Tests/AuthTests.swift, Test/Tests/DeltaCodecTests.swift, Test/Tests/PushTests.swift, Test/Tests/RealtimeClientChannelTests.swift, Test/Tests/RealtimeClientConnectionTests.swift, Test/Tests/RealtimeClientPresenceTests.swift, Test/Tests/RealtimeClientTests.swift, Test/Tests/RestClientChannelTests.swift, Test/Tests/RestClientTests.swift
This is part of #1604 (removing global mutable state in test suite). See commit messages for more details.
=> Remove static `TestProxyTransport` properties

Test/Tests/PushAdminTests.swift
The current logic assumes that the `deviceRegistrations.save` calls will complete in the order that they are started (and hence, that when the final device in the list has been registered, all of the devices have been registered). This is not correct, and means that sometimes we end up trying to create a channel subscription for a device that has not been registered yet, causing the `channelSubscriptions.save` call to fail.
=> Fix wait logic in `PushAdminTests.setUp`

.github/workflows/integration-test-iOS16_2.yaml, .github/workflows/integration-test-macOS.yaml, .github/workflows/integration-test-tvOS16_1.yaml
This contains all of the test reports, including the `.xcresult` bundles which contain rich test-related data such as screenshots and crash reports. Useful for getting further test failure data that isn’t captured in the printed logs, or for debugging the behaviour of the observability server upload script.
=> Upload all Fastlane test output as an artifact

Scripts/upload_test_results.sh
This is a [new crash report format added in iOS 15](https://developer.apple.com/documentation/xcode/interpreting-the-json-format-of-a-crash-report).
https://github.com/ably/test-observability/pull/72 adds a link for downloading the crash report, which can then be viewed in macOS.
Resolves #1688.
=> Upload `.ips` crash reports to observability server

fastlane/Fastfile
I was getting an unhelpful error message when running fastlane without the `ABLY_ENV` environment variable set. This PR refactors the `Fastfile` a bit and then shows a more useful error message when this variable is missing.
=> Tidy up fastlane config

Test/Ably-iOS.xctestplan, Test/Ably-macOS.xctestplan, Test/Ably-tvOS.xctestplan
Som of the test depend or could depend on localized data (example below) 
so the region and language for testing targets should be fixed. 
This change is fixing language to `EN` and region to `United States`
=> Make testing target language and region fixed

Ably.xcodeproj/project.pbxproj, Cartfile.private, Cartfile.resolved, Test/AblyTests-Bridging-Header.h, Test/Dependencies/steipete/Aspects.h, Test/Dependencies/steipete/Aspects.m, Test/Test Utilities/NSObject+TestSuite.m, Test/Test Utilities/NSObject+TestSuite.swift, Test/Test Utilities/TestUtilities.swift, Test/Tests/AuthTests.swift, Test/Tests/RealtimeClientChannelTests.swift, Test/Tests/RealtimeClientConnectionTests.swift, Test/Tests/RealtimeClientPresenceTests.swift, Test/Tests/RestClientChannelTests.swift, Test/Tests/RestClientChannelsTests.swift
Aspects dependency is 9yrs old code and it won't compile with Xcode 14.3 because of it's low deployment target config.
We could fork this repo and change configuration, but this is just one file (and header) so I decided to integrate it into project codebase.
=> Integrate `Aspects` dependency with project codebase

Test/Test Utilities/TestUtilities.swift, Test/Tests/RealtimeClientChannelTests.swift, Test/Tests/RestClientChannelTests.swift, Test/Tests/RestClientChannelsTests.swift, Test/Tests/RestClientTests.swift, Test/Tests/UtilitiesTests.swift
The one I particularly care about is the one in
`TestUtilities.commonAppSetup`, which has caused several crashes in CI when the sandbox is not behaving nicely.
=> Remove some easily-avoidable use of `try!` in tests

Scripts/upload_test_results.sh
To make it easier to find the request in the Heroku logs ([documentation](https://devcenter.heroku.com/articles/http-request-id#how-it-works)).
=> Send an `X-Request-ID` header when uploading test results

Ably-SoakTest-AppUITests/SoakTest.swift, Ably-SoakTest-AppUITests/SoakTestWebSocket.swift, Ably.xcodeproj/project.pbxproj, Source/ARTRealtimeTransportFactory.m, Source/ARTWebSocketFactory.m, Source/ARTWebSocketTransport.m, Source/Ably.modulemap, Source/PrivateHeaders/ARTWebSocketFactory.h, Source/PrivateHeaders/Ably/ARTWebSocket.h, Source/PrivateHeaders/Ably/ARTWebSocketTransport+Private.h, Source/PrivateHeaders/Ably/ARTWebSocketTransport.h, Source/SocketRocket/ARTSRWebSocket.h, Source/SocketRocket/ARTSRWebSocket.m, Source/SocketRocket/Internal/Delegate/ARTSRDelegateController.h, Source/SocketRocket/Internal/Delegate/ARTSRDelegateController.m, Source/include/Ably.modulemap, Test/Test Utilities/TestProxyTransportFactory.swift, Test/Test Utilities/TestUtilities.swift
This refactor will give us more control over the created instance, which will be useful in tests. It removes `ARTWebSocketTransport`’s `webSocketClass` global state. See commit messages for more details.
Part of fixing #1695.
=> Add ability to specify a factory for creating `ARTWebSocket` object

Test/Test Utilities/NSObject+TestSuite.swift, Test/Test Utilities/TestProxyTransportFactory.swift, Test/Test Utilities/TestUtilities.swift
This fixes an intermittent test failure in `RealtimeClientConnectionTests.test__100(...)`.
This failure was introduced by acc66fd. A side effect of the changes in that commit was that after completing execution of the preceding test case (`test__096`), we no longer reset the array-shuffling implementation used by this test. This (for reasons that I haven’t investigated) had the effect of causing the `ARTRealtime` instance created by that test (which for some reason the test decides not to tear down, with a commented justification that I’m not convinced by, but that’s a separate matter) to continue trying to connect even during the execution of `test__100`. In turn, this caused `test__100`’s override of `ARTWebSocket#open` to sometimes (depending on timing) be consumed by `test__096`’s …
=> Remove use of global state for modifying `ARTWebSocket#open`

Source/PrivateHeaders/Ably/ARTAuth+Private.h, Source/PrivateHeaders/Ably/ARTBackoffRetryDelayCalculator.h, Source/PrivateHeaders/Ably/ARTChannelStateChangeMetadata.h, Source/PrivateHeaders/Ably/ARTConnection+Private.h, Source/PrivateHeaders/Ably/ARTConstantRetryDelayCalculator.h, Source/PrivateHeaders/Ably/ARTHttp+Private.h, Source/PrivateHeaders/Ably/ARTInternalLogCore+Testing.h, Source/PrivateHeaders/Ably/ARTLogAdapter+Testing.h, Source/PrivateHeaders/Ably/ARTLogAdapter.h, Source/PrivateHeaders/Ably/ARTPaginatedResult+Subclass.h, Source/PrivateHeaders/Ably/ARTPresenceMap.h, Source/PrivateHeaders/Ably/ARTPush+Private.h, Source/PrivateHeaders/Ably/ARTPushAdmin+Private.h, Source/PrivateHeaders/Ably/ARTPushChannel+Private.h, Source/PrivateHeaders/Ably/ARTPushChannelSubscriptions+Private.h, Source/PrivateHeaders/Ably/ARTPushDeviceRegistrations+Private.h, Source/PrivateHeaders/Ably/ARTRealtimeChannels+Private.h, Source/PrivateHeaders/Ably/ARTRest+Private.h, Source/PrivateHeaders/Ably/ARTRestChannel+Private.h, Source/PrivateHeaders/Ably/ARTRestChannels+Private.h, Source/PrivateHeaders/Ably/ARTRestPresence+Private.h, Source/PrivateHeaders/Ably/ARTTypes+Private.h
Reverts ably/ably-cocoa#1756
Reverting, because compilation errors for Xcode 14.2/14.3 should be addressed instead, see https://github.com/ably/ably-cocoa/issues/1764
=> Revert "Importing headers inside PrivateHeaders folder with module based import."

Source/ARTRealtimeChannel.m
This was a mistake in 47e3a59.
=> Fix parameter in log message

Ably.xcodeproj/project.pbxproj, Test/Test Utilities/DataGatherer.swift, Test/Tests/RealtimeClientChannelTests.swift
This is preparation for modifying `test__131b__Channel__if_the_channel_receives_a_server_initiated_DETACHED_message_and_if_the_attempt_to_reattach_fails_then_the_channel_will_transition_to_SUSPENDED_state_with_periodic_reattach_with_channelRetryTimeout` in #1431.
I didn't find the test very readable in its current state, and this is an attempt at improving that. I've also added assertions about the retry delays, which will become more important when we introduce the backoff and jitter logic.
See commit messages for more details.
=> Improve channel retry tests

Ably.xcodeproj/project.pbxproj, Source/ARTAttachRetryState.m, Source/ARTRealtimeChannel.m, Source/ARTTestClientOptions.m, Source/Ably.modulemap, Source/PrivateHeaders/Ably/ARTAttachRetryState.h, Source/PrivateHeaders/Ably/ARTTestClientOptions.h, Source/include/Ably.modulemap, Test/Tests/AttachRetryStateTests.swift, Test/Tests/RealtimeClientChannelTests.swift
**Note: This PR is based on top of #1611; please review that one first.**
This implements incremental backoff and jitter for channel attach retries, as described by [`RTL13b`](https://sdk.ably.com/builds/ably/specification/main/features/#RTL13b). This is part of #1431.
=> Implement incremental backoff and jitter for channel attach retries

.github/workflows/check-pod.yaml, .github/workflows/docs.yml, .github/workflows/integration-test-iOS16_2.yaml, .github/workflows/integration-test-macOS.yaml, .github/workflows/integration-test-tvOS16_1.yaml, Cartfile.private, Cartfile.resolved, Makefile, Scripts/carthage-with-workaround-for-issue-3019.sh, Source/ARTRealtimePresence.m, Test/Test Utilities/TestUtilities.swift, Test/Tests/AuthTests.swift, Test/Tests/RealtimeClientChannelTests.swift, Test/Tests/RealtimeClientPresenceTests.swift, Test/Tests/RealtimeClientTests.swift, Test/Tests/RestClientChannelsTests.swift, Test/Tests/RestClientPresenceTests.swift, Test/Tests/RestClientTests.swift
Closes #1765, #1766
This contains changes required by Xcode 14.3 (and 15 by the means of https://github.com/ably/ably-cocoa/pull/1801/commits/64967fe59da53e41c45564297167e894e247f683 and https://github.com/ably/ably-cocoa/pull/1801/commits/62fb2335c37dee19b1b3fa8ef70e75ed26a427ff), but not actually switching to macOS 13 for it (Xcode 14.2 accepts those changes just fine).
By switching to macOS 13 explicitly, [known set of tests](https://github.com/ably/ably-cocoa/pull/1760#issuecomment-1606290881) begins to fail on CI, until `ttl` timeout for those tests [increase](https://github.com/ably/ably-cocoa/pull/1799/commits/a1e270a235abd6171dc5804ddd0a0197870874b7) (https://github.com/ably/ably-cocoa/pull/1783, [run](https://github.com/ably/ably-cocoa/actions/runs/6178325306/job/16796412215?pr=17 …
=> [SDK-3644] Preparation for macOS 13

Test/Tests/RestClientTests.swift
=> [SDK-3869] Uppercase PATCH reinforcing

Source/ARTRealtimeChannel.m, Source/ARTTypes.m, Test/Tests/RealtimeClientChannelTests.swift
=> [SDK-3769] Respect rtl12

Source/ARTRealtime.m, Source/ARTWebSocketTransport.m, Source/PrivateHeaders/Ably/ARTRealtimeTransport.h, Test/Test Utilities/TestUtilities.swift, Test/Tests/RealtimeClientConnectionTests.swift
This treats all transport errors as recoverable from the point of view of [RTN14d](https://sdk.ably.com/builds/ably/specification/main/features/#RTN14d).
The immediate reason for doing this is so that an error of OSStatus 9806 (`errSSLClosedAbort`) doesn't cause the client to transition to the `FAILED` state. But, as described in the commit message, this also reflects the broader approach that @paddybyers wants us to take for handling transport errors.
Resolves #1817.
=> [SDK-3926] Treat all transport errors as recoverable

Source/ARTLocalDevice.m, Source/ARTPushActivationState.m, Source/PrivateHeaders/Ably/ARTLocalDevice+Private.h, Test/Tests/PushActivationStateMachineTests.swift
This partially fixes issue #1177 (deregistration does not clear device details) and only resets clientId, since it affects push device registration with a different clientId (after deregistration with previous clientId). This only affects clients that do not restart their apps after deregistration, since clientId is loaded into device once per app launch.
=> Clear clientId after deregistration

Test/Test Utilities/TestUtilities.swift, Test/Tests/AuthTests.swift, Test/Tests/RealtimeClientConnectionTests.swift, Test/Tests/RestClientTests.swift
I’ve noticed these tests intermittently failing on CI. They all wait for the Ably service to consider a token as having expired by waiting for its `ttl` to elapse. However, clock discrepancies between Ably servers might mean that this doesn’t always work. So let’s try adding a bit of a tolerance to the wait and see if it helps.
There are probably other tests that are affected similarly; these are just the ones that caught my eye.
=> Try to reduce failures in some tests that exercise token expiry

Test/Test Utilities/TestUtilities.swift, Test/Tests/RealtimeClientPresenceTests.swift
Closes #1792
Now a separate client is created for the member that will leave during SUSPENDED and ensure that a leave event for this member will be generated upon new attach.
=> [SDK-3814] Refactoring for "test__023__Presence__Channel_state_change_side_effects…"

Source/ARTRest.m, Test/Tests/RestClientTests.swift
Partially addresses #1796 
In a test suite this failure goes as `test__092__RestClient__request__method_signature_and_arguments__should_do_a_request_and_receive_a_valid_response`, i.e. the test which is being executed at the moment when `fail("Completion closure should not be called")` is called [within](https://github.com/ably/ably-cocoa/blob/ca4ffa1f582714945b9f323a1dc86b1da57c974f/Test/Tests/RestClientTests.swift#L1916) `test__090__RestClient__...` test.
Test passes frequently on CI because I assume tests failures after execution not always tracked by XCTest framework. Locally it crashes with this:
```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Attempted to report a test failure to XCTest while no test case was running. The failure was: …
```
=> Fix for "test__090__RestClient__request_…"

Source/PrivateHeaders/Ably/ARTInternalLog.h
Sometimes just one place with `ARTLog*` macros call is needed, so instead of changing `logLevel` you can just make a quick replace with `ARTPrint` and it will be printed into the console regardless of `logLevel` value.
=> Added ARTPrint macros for easier debug.

.github/workflows/integration-test-iOS16_2.yaml, .github/workflows/integration-test-macOS.yaml, .github/workflows/integration-test-tvOS16_1.yaml, Scripts/upload_test_results.sh
Currently, the observability server UI links to the workflow run attempt that the upload corresponds to. This is fine in the case where the workflow only contains a single job, as it currently does in ably-cocoa. But in the case where there’s more than one job in a workflow (e.g. in the case of a matrix build, which we intend to switch ably-cocoa to using in #1311), there’s no way to tell which job an upload corresponds to. So, include this information in the upload.
Copied from https://github.com/ably/test-observability-action/pull/20/commits/d4d651caa532f4a49382c71f08646cb459db461d.
=> Add a link to the GitHub job in observability server upload

.github/workflows/integration-test.yaml, Scripts/upload_test_results.sh
This updates the change made in d7e7736. Copied from test-observability-action commit 518bc5e. Motivation as described in that commit:
> I originally tried implementing this by passing a job-index input, whose
> value was the index to which the current job corresponds in the response
> from the "list jobs for a workflow run attempt" GitHub API. However,
> some experimentation then showed that that the order in which the jobs
> are listed in the action YAML file doesn’t necessarily match that in
> which they are returned from the API, so there was no way to calculate
> the value to pass for job-index. Hence, switched to using the job’s
> `name` instead.
=> Use `name` property to find current job in GitHub API response

Source/ARTRealtimeChannel.m
Closes #1868
based on [RTP1](https://sdk.ably.com/builds/ably/specification/main/features/#RTP1) we shouldn't check on message's `resume` flag when resetting presence map. Also members count check is not necessary either.
=> [SDK-4076] Removed unnecessary checks for RTP1.

Source/ARTRealtime.m
To avoid premature reconnect due to exceeded [threshold](https://github.com/ably/ably-cocoa/blob/913659d50c46a064ef28fbde5e72ea45d09e1d00/Source/ARTRealtime.m#L550) while CONNECTING, reachability now activated after token request is completed. During token request user will receive the request error in case of unreachable network.
Closes #1882
=> Avoiding premature reconnect due to exceeded threshold

Source/ARTConnection.m, Source/ARTRealtime.m, Source/ARTRealtimeChannel.m, Source/PrivateHeaders/Ably/ARTRealtimeChannel+Private.h, Test/Tests/RealtimeClientChannelTests.swift, Test/Tests/RealtimeClientConnectionTests.swift
=> [SDK-4018] Renamed channel's `serial` to `channelSerial`.

Source/ARTRealtimePresence.m, Source/PrivateHeaders/Ably/ARTRealtimePresence+Private.h, Test/Tests/RealtimeClientPresenceTests.swift
=> [SDK-4015] Renamed presence map's `localMembers` to `internalMembers`

Test/Tests/RealtimeClientPresenceTests.swift
Closes #1876 
In this PR I first removed "skipped" from all presence tests and ran it locally. Those that didn't fail ended up in a [loop](https://test-observability.herokuapp.com/repos/ably/ably-cocoa/uploads?branches[]=fix%2F1848-refactoring-presence-looped) a few times. Those that failed twice or more were skipped again. Two tests failed once (051 and 030) and I left them active. I've also left FLAKY label for visibility ([temporarily](https://github.com/ably/ably-cocoa/issues/1887)).
Read commit messages for more. In total 12 (out of 33) presence tests were unskipped.
=> [ECO-4228] Re-enable skipped presence tests

Source/ARTJsonLikeEncoder.m, Source/ARTPushActivationStateMachine.m, Source/include/Ably/ARTEncoder.h, Test/Tests/PushActivationStateMachineTests.swift
=> [ECO-4711] Added `deviceSecret` in device registration POST.

Source/ARTPushActivationState.m, Source/ARTPushActivationStateMachine.m
- clear partial state when CalledDeactivate come to NotActive state (RSH3a1c & RSH3a1d)
- ignore errors with 401 status code and 40005 code (invalid credentials) - (RSH3d2c1)
Will implement RSH3d2b (use `deviceIdentityToken` to perform request) later. The issue for Bank Jago is fixed with the implementation of the spec items above. RSH3d2b just ensures there are no stale/out of sync states between client and server, but the actual push activation/deactivation states are not affected.
=> [ECO-4715] Addresses push notification edge cases

Ably.xcodeproj/project.pbxproj, Source/PrivacyInfo.xcprivacy
Jira [ticket](https://ably.atlassian.net/browse/ECO-4723) holds majority of the information including the urgency of this change.
From a review of the Apple guidelines around this privacy manifest, I believe we need to make clear we collect or use the following (which this PR covers):
- NSUserDefaults (which we use to write and read data solely from this app - `CA92.1` and to provide a wrapper in our SDK which in turn uses NSUserDefaults - `C56D.1`)
- User Data and Device ID (we can and do identify individual clients e.g. by company name within Snowflake for analytics. I've marked we do this for tracking and it is linked to the user)
- ~~Crash Data (this is marked as not being used for tracking (as User Data is more useful for this) but it is still linked to the user)~~
- User Data and …
=> [ECO-4723] Adds required privacy manifest prior to May deadline

Source/ARTGCD.m
=> [ECO-4717] Removed semaphore in favour of an atomic property for synchronised access.

Source/ARTRealtimeChannel.m, Source/PrivateHeaders/Ably/ARTChannelStateChangeParams.h, Test/Tests/RealtimeClientChannelTests.swift
=> Got back `resumed` property in `ARTChannelStateChangeParams` along with the test

Test/Tests/RealtimeClientConnectionTests.swift
`realtimeRequestTimeout` should be longer than sum of `internetIsUp` execution time and `performFakeConnectionError` timeout, otherwise the test will fail, which happens a lot when `internetIsUp` takes longer because of network conditions during some hours (I beleive so).
Closes #1924
=> [ECO-4814] `realtimeRequestTimeout` should be longer

Test/Tests/RealtimeClientChannelTests.swift
=> [ECO-4560] Removed pointless tests

Source/ARTRealtimeChannel.m, Source/ARTRealtimePresence.m, Source/PrivateHeaders/Ably/ARTRealtimePresence+Private.h, Test/Tests/RealtimeClientPresenceTests.swift
Closes #1929 
Introducing `syncInProgress`/`syncInProgress_nosync` pair to properly update call sites for `syncInProgress`.
=> [ECO-4818] Introducing `syncInProgress`/`syncInProgress_nosync` pair

Source/ARTRealtimeChannel.m
=> [ECO-4838] Attach according to RTL7c

Source/ARTRealtime.m, Source/ARTRealtimeChannel.m, Source/PrivateHeaders/Ably/ARTRealtime+Private.h, Source/PrivateHeaders/Ably/ARTRealtimeChannel+Private.h, Test/Tests/RealtimeClientChannelTests.swift, Test/Tests/RealtimeClientConnectionTests.swift, Test/Tests/RealtimeClientPresenceTests.swift, Test/Tests/RestClientChannelTests.swift
Closes #1936, #1938 and #1940
These three bugs were cancelling each other, so it's impossible to address them in different PRs since to fix all the tests failures you need to fix other two bugs. Please see commit messages and review per commit basis.
See also https://github.com/ably/specification/pull/194
Some additional info for commits messages.
d60269af "Proceeding with detach on `CONNECTED`":
What happens here is that in addition to re-attach we need re-detach as well to continue the process after connection becomes `CONNECTED`. But in oppose to `attach` there were no internal method for doing so, that's why I've splitted  `_detach` into `internalDetach:` which doesn't do state check before proceeding with detaching. Also because detach message shouldn't be queued I've removed …
=> [ECO-4858] TO3g compliance

Source/ARTRealtimePresence.m, Source/PrivateHeaders/Ably/ARTRealtimeChannel+Private.h, Test/Tests/RealtimeClientChannelTests.swift, Test/Tests/RealtimeClientPresenceTests.swift
=> [ECO-4838] Enforce RTP6c attach rule for presence.

Source/ARTConnection.m, Source/ARTDefault.m, Source/ARTProtocolMessage.m, Source/ARTQueuedMessage.m, Source/ARTRealtime.m, Source/ARTRealtimeChannel.m, Source/PrivateHeaders/Ably/ARTDefault+Private.h, Source/PrivateHeaders/Ably/ARTProtocolMessage+Private.h, Source/include/Ably/ARTQueuedMessage.h, Test/Tests/AuthTests.swift, Test/Tests/RealtimeClientConnectionTests.swift
Closes #1945 and #1946
`maxMessageSize` wasn't properly respected across the codebase. This fix adds different default values for production/sandbox and properly propogates appropriate value to calculation sites.
=> [ECO-4873] Max message size fix

Source/ARTDefault.m, Test/Tests/AuthTests.swift, Test/Tests/PushAdminTests.swift, Test/Tests/RealtimeClientChannelTests.swift, Test/Tests/RealtimeClientConnectionTests.swift, Test/Tests/RealtimeClientTests.swift, Test/Tests/RestClientChannelTests.swift, Test/Tests/RestClientPresenceTests.swift, Test/Tests/RestClientStatsTests.swift
Closes #1406
All tests were successfully unskipped except "test__105__Connection__Transport_disconnected_side_effects__should_resent_the_DETACH_message_if_there_are_any_pending_channels" that has the same issue as the one described [here](https://github.com/ably/ably-cocoa/issues/1932).
[Results](https://test-observability.herokuapp.com/repos/ably/ably-cocoa/uploads?branches%5B%5D=fix%2F1406-unskip-tests-in-loop) in a loop.
=> [ECO-4365] Unskip all tests

Source/ARTPushActivationState.m, Source/ARTPushActivationStateMachine.m, Source/PrivateHeaders/Ably/ARTPushActivationStateMachine.h, Test/Tests/PushActivationStateMachineTests.swift
Closes #1951 
Made `ARTPushActivationStateNotActivated` to consume `GotPushDeviceDetails` event. Also replaced state machine's `pendingEvents` public property to immutable array. Updatetd RSH3a3 test to check RSH3a3a point.
=> [ECO-4886] respect RSH3a3a

Test/Tests/AuthTests.swift, Test/Tests/PushAdminTests.swift, Test/Tests/RealtimeClientChannelTests.swift, Test/Tests/RealtimeClientConnectionTests.swift, Test/Tests/RealtimeClientPresenceTests.swift, Test/Tests/RealtimeClientTests.swift, Test/Tests/RestClientTests.swift
Replaced all occurences of checking error message instead of error code (or removed where the error code check was already presented) except places where error is locally generated (since it doesn't contain proper error code - 0 usually).
Closes #1946
=> [ECO-4874] Replaced all occurences of checking error message
