ably-ios/ARTJsonEncoder.m, ably-ios/ARTStats.h, ably-ios/ARTStats.m, ably-ios/ably.modulemap, ably.xcodeproj/project.pbxproj, ablySpec/Stats.swift
Add the interval property on ARTStats
Unit tests
=> Specs for ARTStats

ably-ios/ARTAuthTokenParams.h, ably-ios/ARTAuthTokenParams.m, ably-ios/ARTDataQuery.m, ably-ios/ARTHttp.m, ably-ios/ARTJsonEncoder.h, ably-ios/ARTJsonEncoder.m, ably-ios/ARTRest.m, ably-ios/ARTTypes.h, ably-ios/ARTTypes.m
Added timeIntervalToMiliseconds and dateToMiliseconds to avoid different implementations
- Plus: logger wasn't working on ARTJsonEncoder
=> Timestamp fix

ably-ios/ARTAuth.h, ably-ios/Info.plist, ablySpec/Auth.swift
Commit 2f6d463 come from #80 to avoid new branch from `travis-config`.
=> Swift tests: Auth

ably-ios/ARTPayload.m, ably-iosTests/ARTRealtimeCryptoMessageTest.m
=> Payload data either as a JSON Object or Array

ablySpec/Auth.swift, ablySpec/RealtimeClient.connection.swift, ablySpec/TestUtilities.swift
#120: Changed the `MockTransport` name
=> Realtime: test utilities enhancements

ably-ios/ARTWebSocketTransport.h, ably-ios/ARTWebSocketTransport.m, ably-ios/ably.h, ably-ios/ably.modulemap, ably.xcodeproj/project.pbxproj, ably.xcodeproj/xcshareddata/xcschemes/ably.xcscheme, ably.xcodeproj/xcshareddata/xcschemes/ablyTests.xcscheme, ablySpec/Auth.swift, ablySpec/RealtimeClient.channel.swift, ablySpec/RealtimeClient.connection.swift, ablySpec/RealtimeClient.swift, ablySpec/RestChannel.swift, ablySpec/RestClient.channels.swift, ablySpec/RestClient.stats.swift, ablySpec/RestClient.swift, ablySpec/Stats.swift, ablySpec/TestUtilities.swift, ablySpec/ablySpec-Bridging-Header.h
=> Xcode Project enhancements

ably-ios/ARTConnectionDetails.h, ably-ios/ARTConnectionDetails.m, ably-ios/ARTJsonEncoder.m, ably-ios/ARTProtocolMessage+Private.h, ably-ios/ARTProtocolMessage.h, ably-ios/ARTProtocolMessage.m, ably-ios/ARTQueuedMessage.m, ably-ios/ARTRealtime.m, ably-ios/ARTRealtimeChannel.m, ablySpec/Auth.swift
To adjust the public API to the spec.
=> Separate ARTProtocolMessage private parts.

ably.xcodeproj/project.pbxproj
Could resolve some issues on Travis.
=> Product bundle consistency

Podfile, Podfile.lock, ablySpec/RealtimeClientConnection.swift
Great updates:
- https://github.com/Quick/Quick/releases/tag/v0.9.1
- https://github.com/Quick/Nimble/releases/tag/v3.1.0
=> Pods: Quick and Nimble update

ablySpec/ReadmeExamples.swift
Sorry but on every test I needed to wait a couple of minutes.
=> Swift Readme Examples: use Quick

ably-ios/ARTBaseMessage+Private.h, ably-ios/ARTBaseMessage.m, ably-ios/ARTChannel.m, ably-ios/ARTDataEncoder.h, ably-ios/ARTDataEncoder.m, ably-ios/ARTJsonEncoder.m, ably-ios/ARTRealtimeChannel.m, ably-ios/ARTRestChannel.m, ably-ios/ARTRestPresence.m, ably-iosTests/ARTTestUtil.h, ably-iosTests/ARTTestUtil.m, ably.xcodeproj/project.pbxproj, ablySpec/Crypto.swift, ablySpec/RestChannel.swift, ablySpec/TestUtilities.swift
Now testing with fixtures in ably-common.
Fixes #181.
Fixes #195.
=> Fix message encoding and encryption.

ablySpec/RestClientChannels.swift
It is working now.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/ably/ably-ios/222)
=> Remove 'pending' from RSN4 test.

ablySpec/RealtimeClientChannel.swift
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/ably/ably-ios/227)
=> Remove 'pending' from RTL6e1.

ably-ios/ARTRealtime+Private.h, ably-ios/ARTRealtime.m, ablySpec/RealtimeClientChannel.swift, ablySpec/RealtimeClientConnection.swift
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/ably/ably-ios/223)
=> Fix RTL3b and RTL4b.

ably.xcodeproj/project.pbxproj
=> Test suite: fix warning about duplicated class references

Source/ARTConnection.h, Source/ARTRealtime.m, Source/ARTTypes.h, Tests/ARTRealtimeConnectTest.m
Plus, remove a couple of deprecated typedefs.
=> Use ErrorInfo instead of internal ARTStatus in ping callback.

Source/ARTPresenceMap.m, Source/ARTRealtimeChannel.h, Source/ARTRealtimeChannel.m, Source/ARTRealtimePresence.h, Source/ARTRealtimePresence.m
=> Renamed last cb: argument to callback:

Spec/RestClientStats.swift
=> Remove pending from RestClientStats

Spec/Auth.swift, Spec/RealtimeClientChannel.swift, Spec/RealtimeClientPresence.swift, Spec/RestClient.swift, Spec/RestClientChannel.swift, Spec/TestUtilities.swift
=> Test suite: renamed MockHTTPExecutor  to TestProxyHTTPExecutor

Spec/RealtimeClientConnection.swift, Spec/RestClient.swift, Spec/RestClientPresence.swift, Tests/ARTRealtimeConnectTest.m, Tests/ARTRealtimeInitTest.m, Tests/ARTRealtimePresenceTest.m, Tests/ARTRestInitTest.m, Tests/ARTTestUtil.m
I've removed a couple of old failing tests that have more exhaustive,
more maintainable counterparts in the new suite.
=> Several fixes in test suites.

Source/ARTRealtime.m, Source/ARTRealtimeChannel.m, Spec/RealtimeClientChannel.swift, Spec/RealtimeClientConnection.swift
=> Ensure graceful handling of DETACH and DISCONNECT.

Source/ARTRealtime.m, Source/ARTRealtimeTransport.h, Source/ARTRealtimeTransport.m, Source/ARTWebSocketTransport.m, Spec/RealtimeClientConnection.swift, Spec/TestUtilities.swift
=> Move to DISCONNECTED when received "Socket is not connected" error.

Source/ARTRealtime.m, Spec/Auth.swift
As discussed today with @tcard.
=> Fixes 2 crashes that occurs during AblySpec tests execution.

Spec/RestClient.swift
=> Fix RSC10: check  the "otherwise" case

Source/ARTAuth.m, Source/ARTStatus.h, Spec/RestClient.swift
=> Fix issue: should indicate an error if there is no way to renew the token

README.md, Source/ARTJsonLikeEncoder.m, Source/ARTTokenDetails.h, Source/ARTTokenDetails.m, Source/ARTTokenRequest.h, Source/ARTTokenRequest.m, Source/ARTTypes.h, Source/ARTTypes.m, Spec/Auth.swift
Implements ably/docs#193.
Fixes #529.
=> TE6, TD7: Token{Request, Details}::fromJson

Spec/Auth.swift, Spec/RealtimeClientPresence.swift, Spec/RestClientChannel.swift
=> Remove pending tests

Source/ARTHttp.h, Source/ARTRest+Private.h, Source/ARTRest.m, Source/ARTStatus.m, Spec/Auth.swift, Spec/RestClient.swift, Spec/TestUtilities.swift, Spec/Utilities.swift
=> Fix: should decode a protocol message that has an error without a message

.travis.yml, Source/ARTRealtime.m, Source/ARTRealtimeChannel+Private.h, Source/ARTRealtimeChannel.m, Spec/RealtimeClientConnection.swift
=> Fix RTN15c3

Source/ARTChannel.h, Source/ARTChannel.m, Source/ARTJsonLikeEncoder.h, Source/ARTJsonLikeEncoder.m, Source/ARTMessage.h, Source/ARTMessage.m, Source/ARTRest+Private.h, Spec/RestClientChannel.swift, Spec/TestUtilities.swift
=> Add extras field to Message.

Ably.podspec
=> CocoaPod: add `private_header_files` prop

Spec/RealtimeClientChannel.swift, Spec/TestUtilities.swift
=> Fix: when an ATTACH request is responded with a DETACHED

Ably.xcodeproj/project.pbxproj, Source/ARTAuth+Private.h, Source/ARTAuth.m, Source/ARTEventEmitter.m, Source/ARTOSReachability.m, Source/ARTPendingMessage.h, Source/ARTPendingMessage.m, Source/ARTPresenceMap.h, Source/ARTQueuedMessage.h, Source/ARTQueuedMessage.m, Source/ARTRealtime+Private.h, Source/ARTRealtime.m, Source/ARTRealtimeChannel.m, Source/ARTRealtimePresence.m, Source/ARTRealtimeTransport.h, Source/ARTRealtimeTransport.m, Source/ARTRestChannel.m, Source/ARTStatus.h, Source/ARTWebSocketTransport.m, Spec/Auth.swift, Spec/RealtimeClient.swift, Spec/RealtimeClientChannel.swift, Spec/RealtimeClientConnection.swift, Spec/RealtimeClientPresence.swift, Spec/RestClientChannel.swift, Spec/RestClientPresence.swift, Spec/TestUtilities.swift
=> Clean test suite

Source/ARTURLSessionServerTrust.m
=> Fix: check if `NSCFURLSessionConnection` responds to the `performDefaultHandlingForAuthenticationChallenge` selector

Cartfile
=> Pull specific version of SocketRocket

Ably.podspec, Cartfile, Cartfile.resolved
-28 warnings in the project 🍾 
Fix #680
=> Address KSCrash warnings

Ably.xcodeproj/project.pbxproj
=> Remove copy frameworks phase from the Xcode project

.travis.yml
=> Add build of develop branch on Travis

README.md
Otherwise what's on GitHub master doesn't reflect what's released.
=> Clarify release process

Spec/RealtimeClientConnection.swift
=> Improve RTN15G tests

.travis.yml
Maybe it's gonna solve those sporadic cases where all the tests pass but we get an `Exit status: 65`.
=> Use latest version of fastlane on Travis

Spec/Auth.swift
Note: introduced by this 1.1 spec change https://github.com/ably/ably-ios/pull/752/commits/666d53e21d40dbf29a9ee9f855ed97accce8fa38
=> Fix some JWT tests

.travis.yml
I am having inconsistencies between Travis' and my local builds.
Let's use the same version of Cocoapods, to remove doubts about tooling.
=> Update Cocoapods version

.travis.yml, fastlane/Fastfile
Still seeing some inconsistencies between Travis and local tests. Let's uniform also the Xcode version.
Projects settings will be updated in a separate PR.
Update: I threw in also an update to the Simulator version
=> Update Xcode version on Travis

Ably.xcodeproj/xcshareddata/xcschemes/Ably.xcscheme, Ably.xcodeproj/xcshareddata/xcschemes/AblySpec.xcscheme, Spec/PushActivationStateMachine.swift, Spec/RealtimeClientConnection.swift, Spec/RestClient.swift, Spec/RestClientChannel.swift
Fix #721 
Note: the upgrade of the Swift version will be done in a separate PR
=> Update project settings

Spec/TestUtilities.swift
So now you can run tests within Xcode again
=> Fix issue with getEnvironment()

Spec/Auth.swift
=> Allow more leeway for timestamp test

Spec/RestClientStats.swift, Spec/Utilities.swift
=> Remove spec warnings

Spec/PushAdmin.swift
Fix #669 
Following discussion with Paddy, the simplest way is to check that the returned value (`message.data`) contains what's been sent, in a string form.
https://ably-real-time.slack.com/archives/C030C5YLY/p1533895155000008
=> Fix RSH1a test

Spec/RestClient.swift
This slipped through the cracks of this PR https://github.com/ably/ably-ios/pull/777/files
=> Fix RSC7b test

Spec/RestClient.swift, Spec/RestClientChannel.swift
=> Move RSL1i to RestClientChannel file

Spec/RealtimeClientPresence.swift
This contributes to issue https://github.com/ably/ably-ios/issues/767
=> Reactivate and fix RTP17 tests

Source/ARTAuth.m, Source/ARTTokenParams.m, Spec/Auth.swift
=> Fix URL query encoding of Capability and Timestamp fields

Source/ARTAuth.m, Spec/Auth.swift
=> Timestamp should not be generated in the client

Source/ARTPushActivationStateMachine.m, Spec/PushActivationStateMachine.swift
=> Fix Push Update Device Registration

.travis.yml, Source/ARTPush.h
=> Fix Travis CI (iOS 9 build is failing)

Source/ARTJsonLikeEncoder.m, Spec/RealtimeClient.swift
=> Fix milliseconds conversions

Source/ARTPush.m, Spec/Push.swift
=> Push should not sync the local device when it's using the internal queue

Source/ARTChannel.h, Source/ARTChannel.m, Source/ARTPushChannel.m, Source/ARTRealtimeChannel.m, Source/ARTRest+Private.h, Source/ARTRest.m, Source/ARTRestChannel.m, Spec/PushChannel.swift, Spec/TestUtilities.swift
=> Fix Push Channel callbacks

Source/ARTPush.m, Source/ARTPushActivationState.m, Source/ARTPushActivationStateMachine.m
=> Push should use internal logger and avoid system NSLog

Source/ARTProtocolMessage.m, Source/ARTRealtime.m, Source/ARTRealtimeChannel.m, Source/ARTRealtimePresence.m, Source/ARTWebSocketTransport.m, Source/Private/ARTNSString+ARTUtil.h
=> Improve error and debug messages

Source/ARTJsonLikeEncoder.m, Source/ARTLog.m, Source/ARTNSDate+ARTUtil.h, Source/ARTNSDate+ARTUtil.m, Source/ARTPush+Private.h
=> Fix Xcode 11 new warnings

Source/ARTClientOptions.m, Spec/Auth.swift, Spec/Push.swift, Spec/PushActivationStateMachine.swift, Spec/RealtimeClientConnection.swift, Spec/RestClient.swift, Spec/RestClientChannel.swift, Spec/TestUtilities.swift
=> Should not force token auth when clientId is set

Source/Private/ARTOSReachability.m
Fixes #908.
Everything works well in the simulator and the test suite is fine too but the library misses some network changes while testing with a real device.
=> Fix Network Reachability: instance not found for target

Ably.xcodeproj/project.pbxproj, Spec/Crypto.swift, Spec/CryptoTest.m, Spec/RealtimeClientChannel.swift, Spec/TestUtilities.swift
To help with investigating ably/ably-java#531.
Let me know if I'm using the Cocoa crypto class incorrectly!
=> Generation of encrypted test data to verify against Java client

Spec/RealtimeClientConnection.swift
We were asserting that the channel was ATTACHING possibly after it got
to ATTACHED.
Now we put a listener on ATTACHING before simulating the connection
loss that leads to it.
Should fix this test failure:
```
[09:38:12]: ▸     ✗ Connection__connection_failures_once_CONNECTED__System_s_response_to_a_resume_request__CONNECTED_ProtocolMessage_with_a_new_connectionId_and_an_error, expected to equal <Attaching>, got <Attached>
```
=> Fix flaky test for RTN15c3

Source/ARTAuth.m, Source/ARTTokenParams.m
=> Refine fix for RSA8c1b

Makefile, README.md
Nothing massive here but hopefully a few breadcrumbs for those who might be lost (as I often am!).
=> Document development flow

Ably.podspec, Cartfile, Cartfile.resolved, Source/ARTSentry.m
I didn't test #981 as I naively assumed it would be a simple fix. I was wrong.
If this fixes then we can close @tcard's #987.
=> Second Attempt to Update KSCrash dependency

Source/ARTPushActivationState.h, Source/ARTPushActivationState.m, Source/ARTPushActivationStateMachine.m, Spec/PushActivationStateMachine.swift
=> Migrate persisted AfterRegistrationUpdateFailed to ...SyncFailed.

Source/ARTPushActivationState.m, Spec/PushActivationStateMachine.swift
Implements https://github.com/ably/docs/pull/824.
=> Push: Fix activate() behavior while syncing device.

Source/ARTClientOptions.h, Source/ARTClientOptions.m, Source/ARTRestChannel.m, Source/ARTStatus.h, Source/ARTStatus.m, Spec/RestClient.swift, Spec/TestUtilities.swift
=> REST Request IDs

Source/ARTLog.m
=> Allow customers to subclass ARTLog

Source/ARTAuth.m, Source/ARTBaseMessage.m, Source/ARTDataEncoder.m, Source/ARTJsonEncoder.m, Source/ARTProtocolMessage.m, Source/ARTRealtime.m, Spec/RealtimeClientChannel.swift, Spec/TestUtilities.swift, Spec/Utilities.swift
=> Update message bundling regarding RTL6d

Spec/RestClient.swift
I noticed that all tests failed in master so saw the problem and fixed it.
=> Test suite: fix lib version

Spec/Utilities.swift
=> Fix 939: improve EventEmitter tests

Ably.xcodeproj/project.pbxproj, Source/ARTDefault.m, Spec/ARTDefaultTests.swift, Spec/RealtimeClient.swift, Spec/RealtimeClientConnection.swift, Spec/RestClient.swift
In response to [this comment](https://github.com/ably/docs/pull/845#issuecomment-652352048).
=> Bump protocol version to 1.2

CHANGELOG.md, README.md, Source/ARTFormEncode.m, Spec/RealtimeClientChannel.swift
Per [the plan](https://docs.google.com/document/d/1fhbQWQaoIe-urizplgNtT4WxPRgoUDchg-VIBnAEqA0/edit?usp=sharing) (internal link).
=> Rename master to main

Source/ARTAuth+Private.h, Source/ARTAuth.m, Source/ARTRest.m, Spec/Auth.swift, Spec/RestClientChannel.swift
=> REST requests should include X-Ably-ClientId header

Cartfile.private, Cartfile.resolved
https://github.com/ably/ably-cocoa/issues/1123
=> Fix for deprecated linker flag for Nimble framework 

Source/ARTAuth.m, Source/ARTJsonLikeEncoder.m, Source/Private/ARTNSDictionary+ARTDictionaryUtil.h, Source/Private/ARTNSDictionary+ARTDictionaryUtil.m, Spec/Auth.swift, Spec/RealtimeClient.swift, Spec/RealtimeClientConnection.swift, Spec/RestClient.swift, Spec/TestUtilities.swift
=> Accept authURL response with timestamp argument as string

Ably.xcodeproj/project.pbxproj
Resurrection (a bit different) of @ben-xD PR (https://github.com/ably/ably-cocoa/pull/1145) since SocketRocket PR stuck bc of SPM.
=> Remove references to ULID in xcodeproj

Ably.xcodeproj/xcshareddata/xcdebugger/Breakpoints_v2.xcbkptlist
Removed accidentally added Xcode file
=> xcbkptlist removed

Ably.xcodeproj/project.pbxproj, Spec/ObjcppTest.mm
Closes https://github.com/ably/ably-cocoa/issues/968
=> Dummy class in the test suite to check if it compiles with ably-cocoa

Source/ARTJsonLikeEncoder.m, Source/ARTStats.h, Source/ARTStats.m, Spec/Stats.swift
=> New stats fields

Source/ARTAuthOptions.h, Source/ARTChannel.h, Source/ARTChannelOptions.h, Source/ARTClientOptions.h, Source/ARTConnection.h, Source/ARTCrypto.h, Source/ARTHTTPPaginatedResponse.h, Source/ARTMessage.h, Source/ARTPaginatedResult.h, Source/ARTPresenceMessage.h, Source/ARTProtocolMessage.h, Source/ARTRealtime.h, Source/ARTRealtimeChannel.h, Source/ARTRest.h, Source/ARTRestChannel.h, Source/ARTStats.h, Source/ARTStatus.h, Source/ARTTokenDetails.h, Source/ARTTokenParams.h, Source/ARTTokenRequest.h, Source/ARTTypes.h
Closes #298 (keep branch after merge)
=> Copied descriptions from ably.com/documentation/realtime/types

Spec/Auth.swift
I’m guessing a copy-and-paste mistake when writing the tests…
=>  [Groundwork for #1201] Fix test with duplicate name

Docs/tools-for-investigating-test-failures.md
This will help us investigate failures as we work on ably/ably-cocoa#1279.
=> Add documentation about tools for investigating test failures

Spec/Tests/RealtimeClientConnectionTests.swift
=> Added XCTestExpectation to wait for all attemted fallback hosts (test-094)

Scripts/carthage-with-workaround-for-issue-3019.sh
Closes #1485. See commit message for more details.
=> Fix `make carthage_package` when running on an Apple Silicon Mac

Docs/Main.md, Scripts/jazzy.sh
Closes #1498 
https://sdk.ably.com/builds/ably/ably-cocoa/main/jazzydoc/
=>  Added intro blurb to jazzy generated documention

.github/workflows/docs.yml
=> Made this workflow run for all tags

Source/ARTStatus.h
=> Added Ably error codes link to the ARTErrorCode description

Source/ARTRealtimePresence.m, Spec/Tests/RealtimeClientPresenceTests.swift
I've split this from #1515, to extract the part that's needed for fixing https://github.com/ably/ably-asset-tracking-swift/issues/401.
=> Enforce RTP8j spec point

Source/ARTDefault+Private.h, Source/ARTDefault.m
Remove some unused private stuff, make some stuff `static` where possible.
=> Tidy up `ARTDefault` a little

Scripts/set-version.sh
=> Add missed files to `set-version` script

.github/workflows/integration-test-iOS16_2.yaml, README.md, fastlane/Fastfile
=> Fixed CI error due to changed iOS in the environment

Ably.xcodeproj/project.pbxproj, Source/ARTAttachRequestMetadata.m, Source/ARTChannelStateChangeMetadata.m, Source/ARTConnectionStateChangeMetadata.m, Source/ARTRealtime.m, Source/ARTRealtimeChannel.m, Source/ARTRetrySequence.m, Source/Ably.modulemap, Source/PrivateHeaders/Ably/ARTAttachRequestMetadata.h, Source/PrivateHeaders/Ably/ARTChannelStateChangeMetadata.h, Source/PrivateHeaders/Ably/ARTConnectionStateChangeMetadata.h, Source/PrivateHeaders/Ably/ARTRetrySequence.h, Source/include/Ably.modulemap, Test/Test Utilities/MockRetryDelayCalculator.swift, Test/Tests/RetrySequenceTests.swift
A small refactor, groundwork for #1431. See commit messages for more details.
=> Encapsulate retry state in a type

Ably.xcodeproj/project.pbxproj, Source/ARTRealtime.m, Source/ARTRealtimeChannel.m, Source/ARTTypes.m, Source/Ably.modulemap, Source/PrivateHeaders/Ably/ARTTypes+Private.h, Source/include/Ably.modulemap
We’ll use this for testing the upcoming implementation of #1431.
=> Emit retry attempt in state changes

Ably.xcodeproj/project.pbxproj, Source/ARTClientOptions.m, Source/ARTDefault.m, Source/ARTRealtime.m, Source/ARTRealtimeChannel.m, Source/ARTRealtimeChannels.m, Source/ARTRestChannels.m, Source/ARTTestClientOptions.m, Source/Ably.modulemap, Source/PrivateHeaders/Ably/ARTDefault+Private.h, Source/PrivateHeaders/Ably/ARTTestClientOptions.h, Source/include/Ably.modulemap, Test/Test Utilities/TestUtilities.swift, Test/Tests/AuthTests.swift, Test/Tests/PushChannelTests.swift, Test/Tests/RealtimeClientChannelTests.swift, Test/Tests/RealtimeClientChannelsTests.swift, Test/Tests/RealtimeClientConnectionTests.swift, Test/Tests/RealtimeClientPresenceTests.swift, Test/Tests/RestClientChannelTests.swift
Noticed the use of this whilst working on a test case in #1431. Opened #1601 to fix the rest of stuff like this.
=> Remove `+[ARTDefault setRealtimeRequestTimeout]`

Source/ARTCrypto.m, Source/PrivateHeaders/Ably/ARTCrypto+Private.h
This fixes a couple of issues I introduced accidentally in 66ee0f7. See commit messages for more details.
=> Fix a couple of issues introduced in `66ee0f7`

Test/Test Utilities/TestUtilities.swift
This reverts commits 7448758, 38289f6, and 90db2b0. They seem to have introduced intermittent test failures that we haven’t seen before. I’m going to revert for now, and return to it another time with more care. Sorry!
=> Revert contents of PR #1671

Test/Test Utilities/TestUtilities.swift, Test/Tests/RestClientStatsTests.swift
A few tweaks to this test helper class. See commit messages for more details.
=> Tidy up and rename `NSURLSessionServerTrustSync`

Source/ARTRealtime.m
This is initial part of the changes for issue #1626
=> Handle reachability events (preparation)

Test/Test Utilities/JSON.swift, Test/Test Utilities/TestUtilities.swift, Test/Tests/AuthTests.swift, Test/Tests/DeltaCodecTests.swift, Test/Tests/ObjectLifetimesTests.swift, Test/Tests/PushAdminTests.swift, Test/Tests/PushChannelTests.swift, Test/Tests/PushTests.swift, Test/Tests/ReadmeExamplesTests.swift, Test/Tests/RealtimeClientChannelTests.swift, Test/Tests/RealtimeClientChannelsTests.swift, Test/Tests/RealtimeClientConnectionTests.swift, Test/Tests/RealtimeClientPresenceTests.swift, Test/Tests/RealtimeClientTests.swift, Test/Tests/RestClientChannelTests.swift, Test/Tests/RestClientPresenceTests.swift, Test/Tests/RestClientStatsTests.swift, Test/Tests/RestClientTests.swift, Test/Tests/UtilitiesTests.swift
A few improvements to error handling in test setup. See commit messages for more details.
=> Error handling in test setup

.github/workflows/integration-test-iOS16_2.yaml, .github/workflows/integration-test-macOS.yaml, .github/workflows/integration-test-tvOS16_1.yaml, Scripts/log-environment-information.sh
I’ve found myself sometimes wondering things like where the runner machine is located and where the Ably server it’s connected to is located.
=> Log some useful IP addresses in CI

Test/Tests/AuthTests.swift, Test/Tests/RealtimeClientConnectionTests.swift
Resolves #1746. See commit messages for more details.
=> Fix tests broken by `cb7af9d`

README.md
Resolves #1183. See commit messages for more details.
=> Fix linker error upon following `README`’s Carthage instructions

Source/ARTRealtimeTransportFactory.m
In the `#import "ARTWebsocketTransport+Private.h"` line.
Closes #1757
=> Fixed the letter case for the file name

Source/PrivateHeaders/Ably/ARTAuth+Private.h, Source/PrivateHeaders/Ably/ARTBackoffRetryDelayCalculator.h, Source/PrivateHeaders/Ably/ARTChannelStateChangeMetadata.h, Source/PrivateHeaders/Ably/ARTConnection+Private.h, Source/PrivateHeaders/Ably/ARTConstantRetryDelayCalculator.h, Source/PrivateHeaders/Ably/ARTHttp+Private.h, Source/PrivateHeaders/Ably/ARTInternalLogCore+Testing.h, Source/PrivateHeaders/Ably/ARTLogAdapter+Testing.h, Source/PrivateHeaders/Ably/ARTLogAdapter.h, Source/PrivateHeaders/Ably/ARTPaginatedResult+Subclass.h, Source/PrivateHeaders/Ably/ARTPresenceMap.h, Source/PrivateHeaders/Ably/ARTPush+Private.h, Source/PrivateHeaders/Ably/ARTPushAdmin+Private.h, Source/PrivateHeaders/Ably/ARTPushChannel+Private.h, Source/PrivateHeaders/Ably/ARTPushChannelSubscriptions+Private.h, Source/PrivateHeaders/Ably/ARTPushDeviceRegistrations+Private.h, Source/PrivateHeaders/Ably/ARTRealtimeChannels+Private.h, Source/PrivateHeaders/Ably/ARTRest+Private.h, Source/PrivateHeaders/Ably/ARTRestChannel+Private.h, Source/PrivateHeaders/Ably/ARTRestChannels+Private.h, Source/PrivateHeaders/Ably/ARTRestPresence+Private.h, Source/PrivateHeaders/Ably/ARTTypes+Private.h
=> Importing headers inside PrivateHeaders folder with module based import.

Ably.podspec
Part of https://github.com/ably/ably-cocoa/issues/1788
=> Updated podspec to use manual version.

Source/ARTRealtimeChannel.m
=> [SDK-3815] Only emitting the UPDATE in the case where re-entry fails (RTP17e).

Source/ARTTokenRequest.m
=> [SDK-3948] Use safe json dictionary value extraction.

.github/workflows/check-pod.yaml, .github/workflows/examples.yaml, .github/workflows/integration-test.yaml, README.md, Scripts/carthage-with-workaround-for-issue-3019.sh, fastlane/Fastfile
On top of https://github.com/ably/ably-cocoa/pull/1840
=> Transition to Xcode 15.1

Test/Tests/RestClientChannelTests.swift
Closes #1859 
Different "test__047__status__with_subscribers__returns_a_channel_details_object_populated_with_channel_metrics" failure results for various delay value: [0.5](https://test-observability.herokuapp.com/repos/ably/ably-cocoa/uploads?branches%5B%5D=1859-test__047-in-loop), [1.5](https://test-observability.herokuapp.com/repos/ably/ably-cocoa/uploads?branches[]=1859-test__047-in-loop-delay-1.5), [2.5](https://test-observability.herokuapp.com/repos/ably/ably-cocoa/uploads?branches[]=1859-test__047-in-loop-delay-2.5) and for a [poll](https://test-observability.herokuapp.com/repos/ably/ably-cocoa/uploads?branches[]=1859-test__047-in-loop-poll)
=> [SDK-4044] Delay before requesting metrics

Source/ARTPushActivationStateMachine.m
Fixed condition, that check status code of deregistration response
=> fix: typo in deregistration error check condition

CHANGELOG.md
=> fixes changelog typo

Test/Tests/RealtimeClientPresenceTests.swift
Closes #1927 
This test was failing because of race condition - `channel.internal.presence.syncInProgress` is not thread safe. So instead of checking it unreliably I've moved injecting code into the hook for `endSync` to guarantee injecting before the sync ends and checking whether it was properly added right after.
=> [ECO-4816] Refactor for RTP2f test.

Source/ARTEventEmitter.m, Source/ARTPresenceMessage.m, Source/ARTRealtimeChannel.m, Source/ARTRealtimePresence.m, Source/PrivateHeaders/Ably/ARTRealtimeChannel+Private.h, Test/Tests/AuthTests.swift
=> [ECO-4866] Remove code duplication

Source/ARTRealtime.m, Source/ARTTypes.m, Test/Tests/RealtimeClientConnectionTests.swift
Added check on CONNECTING state in the `_connect` method. Added additional fiels to the state description + test.
Closes #1811
=> [ECO-4563] Added check on CONNECTING state in the `_connect` method

.github/workflows/examples.yaml, .github/workflows/integration-test.yaml
this will allow us to manually run tests against sandbox using the github.com UI
=> ci: enable workflow_dispatch
